* 深圳户口类型
** 集体户口
简单来说就是你入深户但是还没有买房，因此要把自己的户籍挂在公司、学校、派出所等地方。

目前深圳这边集体户口主要分以下几类：
- 学校集体户：在深圳上学的小伙伴，可以挂靠目前深圳这边所读学校集体户。
- 公司集体户：上班公司如有公司集体户，政府会强制要求在职人才落户和留学生落户必须落户公司集体户，应届生则直接落户到上班公司注册地址辖区的派出所人才专户（不推荐，离职后得迁出）。
- 派出所代管户（已取消）：只要上班公司没有公司集体户，那在职人才落户和留学生落户都是可以直接落户到公司注册地址辖区的派出所代管户。目前深圳挂靠户口政策有变化，取消派出所代管户，全部变为派出所人才专户。
- 派出所人才专户：国内应届生的落户方式，也是最简单的方式落户深圳。深圳派出所人才专户永久有效免费，国内应届生不需要工作和社保就可以迁入；有社保的在职人才和留学生也可以迁入；目前深圳派出所人才专户是落户挂靠户口最佳的选择。应届生如果在深圳有工作和社保，需要落户到缴纳社保公司辖区派出所人才专户，而不能任意落户深圳一个区，落户时需提供营业执照复印件。

*** 关于人才市场集体户
深圳人才市场集体是接收留学生，不在接收国内应届生和在职人才落户的人群；留学生不需要社保和工作就可以落户罗湖、宝安、龙华和南山的人才市场集体户；
人才市场集体户有效期是两年，到期后需要迁走。

人才市场集体户和派出所人才专户都是深圳的集体户，都是永久有效的深圳户口，落户之后福利待遇都是一样的。

*** 派出所人才专户

*** 参考文章
[[https://www.zhihu.com/question/329739787/answer/1447086030][深圳人才市场集体户和派出所人才专户有什么区别？]]
** 个人户口
个人户口也就是家庭户口，就是我们通常意义上的个人户口了，具备单独立户条件，其户籍关系挂靠在自己或者配偶、直系亲属的房产上的居民户口。

1. 本人房产家庭户
自己在深圳有房产，可以落户自己房产名下。

2. 亲友房产家庭户
如果自己在深圳没有房产，亲朋好友在深圳有房产，并且同意你挂靠户口，那就可以挂靠亲友房产名下。

** 个人户口和集体户口的区别
现在集体户口和个人户口享受的深圳福利、买房买车等权限都是一样的。

入户深圳集体户口之后，派出所会给到我们一个常住人口信息登记卡，这个常住人口信息登记卡包含了我们所有的户籍信息，跟老家户口本的作用是一模一样的，需要开什么档案的证明或是结婚、买房、升学等，直接用这个常住人口信息登记卡即可。

1. 深圳集体户口和个人户口享受深圳基本福利和待遇一样，享受的社保待遇也一样。
2. 结婚问题：深圳集体户结婚需要身份证、常住人口信息登记卡和相关证明去民政局办理。
3. 小孩落户问题：集体户口小孩落户可以落在家长所在的集体户口上，办理落户需要用常住人口信息登记卡+父母双方身份证+父母双方结婚证+另一方户口本+小孩医学出生证明即可。
4. 小孩教育问题：小孩是集体户口的，同深圳个人户口小孩享受一样的教育资源（需要注意：深圳各学校在根据积分入学时，父母有房产的孩子入学更有优势）。

注：目前深圳政府规定在深圳有商品房才能入个人户口，如果亲戚朋友在深圳当地有房，也可以把户口落到其个人户口名下。

** 参考文章
[[https://zhuanlan.zhihu.com/p/130301948][2022年深圳落户政策最全解读]]
** 深圳公司集体户的弊端
公司集体户最大的弊端在于迁出。当你从公司离职时，必须把户口迁出。

人才市场的集体户是不接受深户户口后期迁进去的。只有刚入户落户的时候才能通过代理机构迁入，只能落户下一个公司的集体户或者挂靠在亲朋好友的名下或者迁入派出所。

还有就是随迁有限制，有的人办户口也是为了孩子或者爱人啊之类的。但是你的爱人和孩子又不是公司员工，所以家属基本随迁不了。
*** 参考文章
[[https://zhuanlan.zhihu.com/p/25629517][关于公司集体户的一些看法]]
* 个人户口
户口为住户和人口的总称，计家为户，计人为口。户口即户籍，由公安机关户政管理机构所制作的，用以记载和留存住户人口的基本信息的法律文书。

1958年发布的《中华人民共和国户口登记条例》第二条规定：”中华人民共和国公民，都应当依照本条例的规定履行户口登记。

在中国当前的户口管理中，把以家庭立户的，即以”具有血缘婚姻或收养关系”立户的称为家庭户。

* 集体户口
集体户口是指暂时还不具备单独立户条件，或者暂时还没有办理单独立户手续的居民，其户籍关系挂靠在某一个集体户头上的居民户口。

集体户口的户主是单位,是单位的所在地,居民户口是除了身份证之外最好的身份证明,集体户口不算;
集体户口是在你还是单位的员工的基础上有效,一旦解除合同需要户口迁移;
集体户口不可以个人自己交纳社保,居民户口可以个人交纳;
人口普查时,集体户口不算普查范围内;
孩子入学的时候如果家长是集体户口的,那孩子不享受该地区的义务教育,不算学籍。

集体户口领取的是户口卡，而个人户口领取的是户口本，当然，户口本和户口卡的作用是一样的，他们都是正式户口，都要经过人事局、计生局和公安局盖章批准办理。

* 个人户口和集体户口的区别
1、落户地方的区别;

2、使用与管理的不一样。
集体户顾名思义就是集体人的户口，一般只有事业单位，人才市场，国有企业才有(特殊情况申请的也可能在私营企业与外资合资企业也有)，一般都是企业为了方便引进人才，方便工作调动而设立的，其落户地址一般都是单位的地址。
个人户口是独立的，是有自己的户口本的，个人户口落在集体户的，是没有独立的户口本的，只有自己的本人页。

3、户口本的区别。
相信大家都看过家庭的户口本，有首页，有个人页。集体户就好像一个很大的家庭户口本一样，户是谁，只有一个的，其它人的都是个人页，但人与人的关系就不是亲属关系了。
因为集体户的人多了，为了规定集体户的运作与使用，集体户的管理单位肯定会作出相应的管理规定，规定了大家的权利与义务。

* 集体户口转独立户口
集体户口是指暂时还不具备单独立户条件，或者暂时还没有办理单独立户手续的居民，其户藉关系挂靠在某一个集体户头上的居民户口。
单独立户必须具有固定的住所，而你现在已经购买了房子，理所当然可以将户口从集体户口中迁出单独立户。

如果自己买房子之后，想要将集体户口转成独立户口的话，流程还是比较简单的，但是我们需要提供一些材料。
1. 房产证原件及复印件（有贷款的为购房合同原件及复印件），
2. 购房发票所有的，原件及复印件，
3. 本人集体户口卡原件，此件没收不退，
4. 本人身份证原件。想要新立户的话还需物业开一张证明，另外非明示所有权人，需提供证明亲属关系的材料，结婚证、出生证之类的证明。

* 参考文章
[[https://zhuanlan.zhihu.com/p/29040852][个人户口是什么，跟集体户口有什么区别？]]
