* 山河大地已属微尘,而况尘中之尘；血肉之躯且归泡影,而况影外之影.非上上智,无了了心。--《莱根谭》

* 我也说不准究竟是在什么时候，什么地点，看见了你什么样的风姿，听到了你什么样的谈吐，便使我开始爱上了你。那是好久以前的事了，等我发现我自己开始爱上了你的时候，我已经走了一半的路了。--《傲慢与偏见》

* 我的天空里没有太阳，总是黑夜，但并不暗，因为有东西代替了太阳。虽然没有太阳那么明亮，但对我来说已经足够。凭借着这份光，我便能把黑夜当成白天。我从来就没有太阳，所以不怕失去。--《白夜行》

* 这是我选择沉默的主要原因之一：从话语中，你很少能学到人性，从沉默中却能。假如还想学得更多，那就要继续一声不吭。--《沉默的大多数》

* 孤独只存在于孤独之中，一旦分担，它就蒸发了。--《当尼采哭泣》

* 生如夏花，逝如冬雪。
人生如此，何悔何怨。

* 长夜将至，我从今开始守望，至死方休。我将不娶妻、不封地、不生子。我将不戴宝冠，不争荣宠。我将尽忠职守，生死於斯。我是黑暗中的利剑，长城上的守卫。我是抵御寒冷的烈焰，破晓时分的光线，唤醒眠者的号角，守护王国的坚盾。我将生命与荣耀献给守夜人，今夜如此，夜夜皆然。

"Night gathers, and now my watch begins. It shall not end until my death. I shall take no wife, hold no lands, father no children. I shall wear no crowns and win no glory. I shall live and die at my post. I am the sword in the darkness. I am the watcher on the walls. I am the fire that burns against the cold, the light that brings the dawn, the horn that wakes the sleepers, the shield that guards the realms of men. I pledge my life and honor to the Night's Watch, for this night and all the nights to come."

* We're not walking in the dark.We are the dark.
我们不是行走于黑暗，我们就是黑暗本身。

* “我酒量一斤，跟你喝，两斤吧。”
“我酒量二两，陪你喝，舍命。”

* 成功只有一个，按照自己的方式度过一生----《明朝那些事儿》

* 人生苦短，因为人生甜长。

* 君子藏器于身，待时而动。

* 凡心所向，素履以往；生如逆旅，一苇以航。

* 但行好事，莫问前程。

* 天空一无所有
为何给我安慰？

* 中国的强大在于中国人从骨子里就认为自己应该强大，并为之不懈奋斗。

* 挽狂澜于既倒，扶大厦之将倾。

* 岁月终究是成就你。

* 你年轻时很美丽，不过跟那时相比，我更喜欢现在你经历了沧桑的容颜。

* 轻用其芒，动即有伤，是为凶器；深藏若拙，临机取决，是为利器。

* 我知道他想跑，可跑不掉，很无助，我很欣赏。

* 我走过最长的路，就是你的套路。

* 诗经
野有死麕①，白茅包之②。有女怀春③，吉士④诱之。
林有朴樕⑤，野有死鹿。白茅纯束⑥，有女如玉。
舒而脱脱兮！⑦无感我帨兮！⑧无使尨⑨也吠！
① 麕（jūn）：同“麇（jūn）”，也可用“野有死麇”，獐子。比鹿小，无角。
② 白茅：草名。属禾本科。在阴历三四月间开白花。包：古音读bǒu。
③ 怀春：思春，男女情欲萌动。
④ 吉士：男子的美称。
⑤ 朴樕（sù）：小木，灌木。
⑥纯束：捆扎，包裹。“纯”为“稇（kǔn）”的假借。
⑦舒：舒缓。脱脱（duì）：动作文雅舒缓。
⑧ 感（hàn）：通假字，通：撼 ，动摇。帨（shuì）：佩巾，围腰，围裙。
⑨尨（máng）：多毛的狗。[2]

* 《论语·泰伯第六》
曾子曰：“可以托六尺之孤，可以寄百里之命，临大节而不可夺也。君子人与？君子人也。”

* 望江南，李煜
多少恨，昨夜梦魂中。还似旧时游上苑，车如流水马如龙。花月正春风。

* 咏菊，唐，黄巢
待得秋来九月八，我花开时百花杀。
冲天香阵透长安，满城尽带黄金甲。

* 唐·罗隐《自遣》
得即高歌失即休，多愁多恨亦悠悠。
今朝有酒今朝醉，明日愁来明日愁
* 唐·黄蘖禅师《上堂开示颂》
尘劳回脱事非常，紧把绳头做一场。
不经一番寒彻骨，那得梅花扑鼻香。
* 唐.崔郊《赠去婢》
公子王孙逐后尘，绿珠垂泪滴罗巾。
侯门一入深如海，从此萧郎是路人。

* 唐·曹松《己亥岁》
泽国江山入战图，生民何计乐樵苏。
凭君莫话封侯事，一将功成万骨枯。

* 年年岁岁花相似，岁岁年年人不同
* 献钱尚父（唐） 贯休
贵逼人来不自由，龙骧凤翥势难收。
满堂花醉三千客，一剑霜寒十四州。
鼓角揭天嘉气冷，风涛动地海山秋。
东南永作金天柱，谁羡当时万户侯。

余孤云野鹤，何天不可飞？
* 长安旅情，唐，孟郊
尽说青云路，有足皆可至。我马亦四蹄，出门似无地。
玉京十二楼，峨峨倚青翠。下有千朱门，何门荐孤士。

* 赠李白,唐,杜甫
秋来相顾尚飘蓬，未就丹砂愧葛洪。
痛饮狂歌空度日，飞扬跋扈为谁雄？
* 唐·孟郊《登科后》
昔日齷齪不足夸，今朝放荡思无崖。
春风得意马蹄疾，一日看尽长安花。

* 唐.秦韬玉《贫女》
蓬门未识绮罗香，拟托良媒益自伤。
谁爱风流高格调，共怜时世俭梳妆。
敢将十指夸针巧，不把双眉斗画长。
苦恨年年压金线，为他人作嫁衣裳。

* 子夜吴歌·秋歌，李白
长安一片月，万户捣衣声。
秋风吹不尽，总是玉关情。
何日平胡虏，良人罢远征。
* 忆秦娥·箫声咽，李白，唐代
箫声咽，秦娥梦断秦楼月。秦楼月，年年柳色，灞陵伤别。
乐游原上清秋节，咸阳古道音尘绝。音尘绝，西风残照，汉家陵阙。
* 逍遥游
意气凌霄不知愁，
愿上玉京十二楼。
挥剑破云迎星落，
举酒高歌引凤游。
千载太虚无非梦，
一段衷情不肯休。
梦醒人间看微雨，
江山还似旧温柔。

* 满江红，岳飞
怒发冲冠，凭阑处、潇潇雨歇。抬望眼、仰天长啸，壮怀激烈。三十功名尘与土，八千里路云和月。莫等闲，白了少年头，空悲切。
靖康耻，犹未雪；臣子恨，何时灭。驾长车，踏破贺兰山缺。壮志饥餐胡虏肉，笑谈渴饮匈奴血。待从头、收拾旧山河，朝天阙。

* 宋.杨万里《竹枝歌》
月子弯弯照九州，几家欢乐几家愁;
几家夫妇同罗帐，几个飘零在外头。

* 破阵子·为陈同甫赋壮词以寄之，宋代，辛弃疾
醉里挑灯看剑，梦回吹角连营。八百里分麾下灸，五十弦翻塞外声。沙场秋点兵。
马作的卢飞快，弓如霹雳弦惊。了却君王天下事，嬴得生前身后名。可怜白发生！

* 青玉案·元夕，宋代，辛弃疾
东风夜放花千树，更吹落，星如雨。宝马雕车香满路，凤箫声动，玉壶光转，一夜鱼龙舞。
蛾儿雪柳黄金缕，笑语盈盈暗香去。众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。

* 永遇乐·京口北固亭怀古，宋代，辛弃疾
千古江山，英雄无觅，孙仲谋处。舞榭歌台，风流总被，雨打风吹去。斜阳草树，寻常巷陌，人道寄奴曾住。想当年，金戈铁马，气吞万里如虎。
元嘉草草，封狼居胥，赢得仓皇北顾。四十三年，望中犹记，烽火扬州路。可堪回首，佛狸祠下，一片神鸦社鼓。凭谁问：廉颇老矣，尚能饭否？

* 宋.黄庭坚《竹枝词》
浮云一百八盘萦，落日四十八渡明。
鬼门关外莫言远，四海一家皆弟兄。
* 宋.赵恒《励学篇》
出门莫恨无人随，书中车马多如簇。
娶妻莫恨无良媒，书中自有颜如玉。
* 宋.陶谷《自嘲》
官职须由生处有，才能不管用时无。
堪笑翰林陶学士，年年依样画葫芦。
* 宋.苏轼《戏张先》
十八新娘八十郎，苍苍白发对红妆。
鸳鸯被里成双夜，一树梨花压海棠。
* 宋·夏元鼎《绝句》
崆峒访道至湘湖，万卷诗书看转愚。
踏破铁鞋无觅处，得来全不费工夫。
* 宋.范仲淹《扇示门人》
一派青山景色幽，前人田地后人收。
后人收得休欢喜，还有收人在后头。
* 寄黄几复,宋,黄庭坚
我居北海君南海，寄雁传书谢不能。
桃李春风一杯酒，江湖夜雨十年灯。
持家但有四立壁，治病不蕲三折肱。
想见读书头已白，隔溪猿哭瘴溪藤。
* 元·李开先《宝剑记》
欲送登高千里目，愁云低锁衡阳路。
鱼书不至雁无凭，今番欲作悲秋赋。
回首西山又日斜，天涯孤客真难度，
男儿有泪不轻弹，只是未到伤心处！

* 明 .于谦《入京》
绢帕蘑菇与线香，本资民用反为殃；
清风两袖朝天去，免得闾阎话短长。
* 咏菊，明，朱元璋
百花发时我不发，我若发时都吓杀。
要与西风战一场，遍身穿就黄金甲。

* 清·黄增
《集杭州俗语诗》
色不迷人人自迷，情人眼里出西施。
有缘千里来相会，三笑徒然当一痴。

* 清.陈于之《题桃花扇》

玉树歌残声已陈， 南朝宫殿柳条新；
福王少小风流惯， 不爱江山爱美人。

* 绮怀十六首(其十四)
【清】黄仲则
几回花下坐吹箫,银汉红墙入望遥。
似此星辰非昨夜,为谁风露立中宵。
缠绵思尽抽残茧,宛转心伤剥后蕉。
三五时年三五月,可怜杯酒不曾消。

* 清.黄景仁《杂感》

仙佛茫茫两未成，只知独夜不平鸣。
风蓬飘尽悲歌气，泥絮沾来薄幸名。
十有九人堪白眼，百无一用是书生。
莫因诗卷愁成谶，春鸟秋虫自作声。

* 清.龚自珍《夜作》

沉沉心事北南东，一睨人材海内空。
壮岁始参周史席，髫年惜堕晋贤风。
功高拜将成仙外，才尽回肠荡气中。
万一禅关砉然破，美人如玉剑如虹。

* 浣溪沙,清,纳兰性德
浮萍漂泊本无根，天涯游子君莫问。
* 雨巷，近代，戴望舒

撑着油纸伞，独自
彷徨在悠长、悠长
又寂寥的雨巷，
我希望逢着
一个丁香一样的
结着愁怨的姑娘。

她是有
丁香一样的颜色，
丁香一样的芬芳，
丁香一样的忧愁，
在雨中哀怨，
哀怨又彷徨；

她彷徨在寂寥的雨巷，
撑着油纸伞
像我一样，
像我一样地
默默踟躇着
冷漠、凄清，又惆怅。

她默默地走近，
走近，又投出
太息一般的眼光
她飘过
像梦一般地，
像梦一般地凄婉迷茫。

像梦中飘过
一枝丁香地，
我身旁飘过这个女郎；
她静默地远了，远了，
到了颓圮的篱墙，
走尽这雨巷。

在雨的哀曲里，
消了她的颜色，
散了她的芬芳，
消散了，甚至她的
太息般的眼光
丁香般的惆怅。

撑着油纸伞，独自
彷徨在悠长、悠长
又寂寥的雨巷，
我希望飘过
一个丁香一样的
结着愁怨的姑娘
* 毛泽东《清平乐·六盘山》
天高云淡，望断南飞雁。不到长城非好汉，屈指行程二万。
六盘山上高峰，红旗漫卷西风。今日长缨在手，何时缚住苍龙？

* 《桃花扇》，孔尚任
俺曾见金陵玉殿莺啼晓，秦淮水榭花开早，谁知道容易冰消！眼看他起朱楼，眼看他宴宾客，眼看他楼塌了！这青苔碧瓦堆，俺曾睡风流觉，将五十年兴亡看饱。那乌衣巷不姓王，莫愁湖鬼夜哭，凤凰台栖枭鸟。残山梦最真，旧境丢难掉，不信这舆图换稿！诌一套《哀江南》，放悲声唱到老。

* 杨涟血书
仁义一生，死于诏狱，难言不得死所，何憾于天，何怨于人？
唯我身副宪臣，曾受顾命，孔子云：托孤寄命，临大节而不可夺。
持此一念，终可见先帝于在天，对二祖十宗于皇天后土，天下万世矣！
大笑大笑还大笑，刀砍东风，于我何有哉？
涟即身无完骨，尸供蛆蚁，原所甘心。但愿国家强固，圣德明，海内长享太平之福。此痴愚念头，至死不改。
70上海特别亮，到处都有光。我觉得只要我站在光里，我就能虚张声势，我就能咬着牙。我活的特别坚强，我觉得我这么多年都过来了，我受了这么多的苦，我受了这么多的气，我觉得我什么都不怕。可是我还是怕，我特别怕。

* 苦昼短
李贺（唐）
飞光飞光，劝尔一杯酒。
吾不识青天高，黄地厚，
唯见月寒日暖，来煎人寿。
食熊则肥，食蛙则瘦。
神君何在，太一安有。
天东有若木，下置衔烛龙。
吾将斩龙足，嚼龙肉。
使之朝不得回，夜不得伏。
自然老者不死，少者不哭。
何为服黄金，吞白玉。
谁似任公子，云中骑碧驴。
刘彻茂陵多滞骨，
嬴政梓棺费鲍鱼。
* 六州歌头·少年侠气
北宋，贺铸
少年侠气，交结五都雄。肝胆洞，毛发耸。立谈中，死生同。一诺千金重。推翘勇，矜豪纵。轻盖拥，联飞鞚，斗城东。轰饮酒垆，春色浮寒瓮，吸海垂虹。闻呼鹰嗾犬，白羽摘雕弓，狡穴俄空。乐匆匆。似黄粱梦。辞丹凤，明月共，漾孤篷。官兄从，怀倥偬，落尘笼。簿书丛。鹖弁如云众。供粗用，忽奇功。笳鼓动，渔阳弄，思悲翁。不请长缨，系取天骄种，剑吼西风。恨登山临水，手寄七弦桐，目送归鸿。
* 昨日国家公祭，淡淡华音，浓浓耻悲。

当年国弱被欺，百死成殇，今日虎狼环伺，怎敢忘怀。工业立国，工业富国，工业强国，前三十年卧薪尝胆建立工业体系，后三十年埋头忍辱多路破茧出局，如今百种工业指标，领先者不足半数，前路漫漫，任重道远，煌煌中华，舍我其谁，寄望年轻人莫松懈，莫迟疑，携后发优势，牢牢奠定工业根基，令国力独步天下，令国威远震重洋，方不负千百年汉唐家风，不负工业人拳拳之心。
* 故曰，域民不以封疆之界，固国不以山溪之险，威天下不以兵革之利。得道者多助，失道者寡助。寡助之至，亲戚畔之；多助之至，天下顺之。以天下之所顺，攻亲戚之所畔；故君子有不战，战必胜矣。
* 侠客行，李白，唐
赵客缦胡缨，吴钩霜雪明。
银鞍照白马，飒沓如流星。
十步杀一人，千里不留行。
事了拂衣去，深藏身与名。
闲过信陵饮，脱剑膝前横。
将炙啖朱亥，持觞劝侯嬴。
三杯吐然诺，五岳倒为轻。
眼花耳热后，意气素霓生。
救赵挥金槌，邯郸先震惊。
千秋二壮士，烜赫大梁城。
纵死侠骨香，不惭世上英。
谁能书阁下，白首太玄经。

* 蝶恋花·伫倚危楼风细细，柳永，宋
伫倚危楼风细细。望极春愁，黯黯生天际。草色烟光残照里。无言谁会凭阑意。
拟把疏狂图一醉。对酒当歌，强乐还无味。衣带渐宽终不悔。为伊消得人憔悴。

* 天下风云出我辈， 一入江湖岁月催；
皇图霸业谈笑间， 不胜人生一场醉。
提剑跨骑挥鬼雨， 白骨如山鸟惊飞;
尘事如潮人如水， 只叹江湖几人回。

* 古之所谓豪杰之士，必有过人之节、人情有所不能忍者。匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒；此其所挟持者甚大，而其志甚远也。

* 鲁迅： 热风·随感录四十一
从一封匿名信里看见一句话，是“数麻石片”(原注江苏方言)，大约是没有本领便不必提倡改革，不如去数石片的好的意思。因此又记起了本志通信栏内所载四川方言的“洗煤炭”。想来别省方言中，相类的话还多；守着这专劝人自暴自弃的格言的人，也怕并不少。

凡中国人说一句话，做一件事，倘与传来的积习有若干抵触，须一个斤斗便告成功，才有立足的处所；而且被恭维得烙铁一般热。否则免不了标新立异的罪名，不许说话；或者竟成了大逆不道，为天地所不容。这一种人，从前本可以夷到九族，连累邻居；现在却不过是几封匿名信罢了。但意志略略薄弱的人便不免因此萎缩，不知不觉的也入了“数麻石片”党。

所以现在的中国，社会上毫无改革，学术上没有发明，美术上也没有创作；至于多人继续的研究，前仆后继的探险，那更不必提了。国人的事业，大抵是专谋时式的成功的经营，以及对于一切的冷笑。

但冷笑的人，虽然反对改革，却又未必有保守的能力：即如文字一面，白话固然看不上眼，古文也不甚提得起笔。照他的学说，本该去“数麻石片”了；他却又不然，只是莫名其妙的冷笑。

中国的人，大抵在如此空气里成功，在如此空气里萎缩腐败，以至老死。

我想，人猿同源的学说，大约可以毫无疑义了。但我不懂，何以从前的古猴子，不都努力变人，却到现在还留着子孙，变把戏给人看。还是那时竟没有一匹想站起来学说人话呢?还是虽然有了几匹，却终被猴子社会攻击他标新立异，都咬死了；所以终于不能进化呢?

尼采式的超人，虽然太觉渺茫，但就世界观有人种的事实看来，却可以确信将来总有尤为高尚尤近圆满的人类出现。到那时候，类人猿上面，怕要添出“类猿人”这一个名词。

所以我时常害怕，愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。

此后如竟没有炬火：我便是唯一的光。倘若有了炬火，出了太阳，我们自然心悦诚服的消失。不但毫无不平，而且还要随喜赞美这炬火或太阳；因为他照了人类，连我都在内。

我又愿中国青年都只是向上走，不必理会这冷笑和暗箭。尼采说：“真的，人是一个浊流。应该是海了，能容这浊流使他干净。

“咄，我教你们超人：这便是海，在他这里，能容下你们的大侮蔑。”(《札拉图如是说》的《序言》第三节)

纵令不过一洼浅水，也可以学学大海；横坚都是水，可以相通。几粒石子，任他们暗地里掷来；几滴秽水，任他们从背后泼来就是了。

这还算不到“大侮蔑”——因为大侮蔑也须有胆力。


最后改编鲁迅的一句话：无论在哪个年代，总有些埋头苦干、踏实肯干的人，兢兢业业，全力以赴的人；也有些敷衍塞责、草草了事之人，侥幸应付、得过且过之人，虽然这浮华的时代可能让后者一时占尽了风光，但却最终掩盖不住前者们的光耀，认真，你就赢了

* 陶者,梅尧臣，宋
陶尽门前土，屋上无片瓦。 十指不沾泥，鳞鳞居大厦。

* 读孟尝君传,王安石，宋
世皆称孟尝君能得士，士以故归之，而卒赖其力以脱于虎豹之秦。嗟乎！孟尝君特鸡鸣狗盗之雄耳，岂足以言得士？不然，擅齐之强，得一士焉，宜可以南面而制秦，尚何取鸡鸣狗盗之力哉？夫鸡鸣狗盗之出其门，此士之所以不至也。

* 梦游天姥吟留别,李白,唐
海客谈瀛洲，烟涛微茫信难求。
越人语天姥，云霞明灭或可睹。
天姥连天向天横，势拔五岳掩赤城。
天台四万八千丈，对此欲倒东南倾。
我欲因之梦吴越，一夜飞度镜湖月。
湖月照我影，送我至剡溪。
谢公宿处今尚在，渌水荡漾清猿啼。
脚著谢公屐，身登青云梯。
半壁见海日，空中闻天鸡。
千岩万转路不定，迷花倚石忽已暝。
熊咆龙吟殷岩泉，栗深林兮惊层巅。
云青青兮欲雨，水澹澹兮生烟。
列缺霹雳，丘峦崩摧。洞天石扉，訇然中开。
青冥浩荡不见底，日月照耀金银台。
霓为衣兮风为马，云之君兮纷纷而来下。
虎鼓瑟兮鸾回车，仙之人兮列如麻。
忽魂悸以魄动，恍惊起而长嗟。
惟觉时之枕席，失向来之烟霞。
世间行乐亦如此，古来万事东流水。
别君去时何时还，且放白鹿青崖间，
须行即骑访名山。安能摧眉折腰事权贵，
使我不得开心颜。

* 蜀道难，李白，唐
噫吁嚱，危乎高哉！蜀道之难，难于上青天！
蚕丛及鱼凫，开国何茫然！
尔来四万八千岁，不与秦塞通人烟。
西当太白有鸟道，可以横绝峨眉巅。
地崩山摧壮士死，然后天梯石栈相钩连。
上有六龙回日之高标，下有冲波逆折之回川。
黄鹤之飞尚不得过，猿猱欲度愁攀援。
青泥何盘盘，百步九折萦岩峦。
扪参历井仰胁息，以手抚膺坐长叹。
问君西游何时还？畏途巉岩不可攀。
但见悲鸟号古木，雄飞雌从绕林间。
又闻子规啼夜月，愁空山。
蜀道之难,难于上青天，使人听此凋朱颜！
连峰去天不盈尺，枯松倒挂倚绝壁。
飞湍瀑流争喧豗，砯崖转石万壑雷。
其险也如此，嗟尔远道之人胡为乎来哉！(也若此 一作：也如此)
剑阁峥嵘而崔嵬，一夫当关，万夫莫开。
所守或匪亲，化为狼与豺。
朝避猛虎，夕避长蛇；磨牙吮血，杀人如麻。
锦城虽云乐，不如早还家。
蜀道之难,难于上青天，侧身西望长咨嗟！

* 此去西洋,深知中国自强之计,舍此无所他求；背负国家之未来,取尽洋人之科学,赴七万里长途,别祖国父母之邦,奋然无悔！

* 浪淘沙令·帘外雨潺潺，李煜，五代
帘外雨潺潺，春意阑珊。罗衾不耐五更寒。梦里不知身是客，一晌贪欢。
独自莫凭栏，无限江山，别时容易见时难。流水落花春去也，天上人间。

* 天之道，其犹张弓与！高者抑之，下者举之，有余者损之，不足者与之，天之道损有余而补不足。人道则不然，损不足，奉有余。孰能有余以奉天下？其唯有道者。

* 无论你叫杉菜还是叫酸菜，听起来都蛮朴实的，所以说呢也希望你获得的，也是朴朴实实的普普通通的，平平凡凡的真爱，也可能在之前，你演绎了无数的爱情。但是，就是希望有一天能够看到你脸上露出真正的、不是剧本里的笑容。无论你的选择与否，我都真诚的祝福你！希望你一生幸福，谢谢！

* 枫桥夜泊 / 夜泊枫江
【作者】张继【朝代】唐
月落乌啼霜满天，江枫渔火对愁眠。
姑苏城外寒山寺，夜半钟声到客船。

* 风云
金鳞岂是池中物,
一遇风云便化龙,
九霄龙吟惊天变,
风云际会浅水游。

* 程浩
命运嘛，休论公道！
真正牛逼的，不是那些可以随口拿来夸耀的事迹，而是那些在困境中依然保持微笑的凡人。
罗永浩有一句话，深得我心：“牛逼的人生，不需要解释。”

* 尼采：“凡不能毁灭我的，必使我强大。

* 唐雎不辱使命
秦王使人谓安陵君曰：“寡人欲以五百里之地易安陵，安陵君其许寡人！”安陵君曰：“大王加惠，以大易小，甚善；虽然，受地于先王，愿终守之，弗敢易！”秦王不说。安陵君因使唐雎使于秦。
秦王谓唐雎曰：“寡人以五百里之地易安陵，安陵君不听寡人，何也？且秦灭韩亡魏，而君以五十里之地存者，以君为长者，故不错意也。今吾以十倍之地，请广于君，而君逆寡人者，轻寡人与？”唐雎对曰：“否，非若是也。安陵君受地于先王而守之，虽千里不敢易也，岂直五百里哉？”
秦王怫然怒，谓唐雎曰：“公亦尝闻天子之怒乎？”唐雎对曰：“臣未尝闻也。”秦王曰：“天子之怒，伏尸百万，流血千里。”唐雎曰：“大王尝闻布衣之怒乎？”秦王曰：“布衣之怒，亦免冠徒跣，以头抢地耳。”唐雎曰：“此庸夫之怒也，非士之怒也。夫专诸之刺王僚也，彗星袭月；聂政之刺韩傀也，白虹贯日；要离之刺庆忌也，仓鹰击于殿上。此三子者，皆布衣之士也，怀怒未发，休祲降于天，与臣而将四矣。若士必怒，伏尸二人，流血五步，天下缟素，今日是也。”挺剑而起。
秦王色挠，长跪而谢之曰：“先生坐！何至于此！寡人谕矣：夫韩、魏灭亡，而安陵以五十里之地存者，徒以有先生也。”

* 七律·和郭沫若同志，毛泽东
一从大地起风雷，便有精生白骨堆。
僧是愚氓犹可训，妖为鬼蜮必成灾。
金猴奋起千钧棒，玉宇澄清万里埃。
今日欢呼孙大圣，只缘妖雾又重来。

* 水调歌头·重上井冈山，毛泽东
久有凌云志，重上井冈山。
千里来寻故地，旧貌变新颜。
到处莺歌燕舞，更有潺潺流水，高路入云端。
过了黄洋界，险处不须看。
风雷动，旌旗奋，是人寰。
三十八年过去，弹指一挥间。
可上九天揽月，可下五洋捉鳖，谈笑凯歌还。
世上无难事，只要肯登攀。

* 坐待时机自主张

* 龟虽寿，曹操
神龟虽寿，犹有竟时。
螣蛇乘雾，终为土灰。
老骥伏枥，志在千里。
烈士暮年，壮心不已。
盈缩之期，不但在天；
养怡之福，可得永年。
幸甚至哉，歌以咏志。

* 短歌行，曹操
对酒当歌，人生几何！譬如朝露，去日苦多。
慨当以慷，忧思难忘。何以解忧？唯有杜康。
青青子衿，悠悠我心。但为君故，沉吟至今。
呦呦鹿鸣，食野之苹。我有嘉宾，鼓瑟吹笙。
明明如月，何时可掇？忧从中来，不可断绝。
越陌度阡，枉用相存。契阔谈讌，心念旧恩。(谈讌 一作：谈宴)
月明星稀，乌鹊南飞。绕树三匝，何枝可依？
山不厌高，海不厌深。周公吐哺，天下归心。(海 一作：水)

* 防祸于先而不致于后伤情。知而慎行，君子不立于危墙之下，焉可等闲视之。

* 沁园春·长沙
独立寒秋，湘江北去，橘子洲头。
看万山红遍，层林尽染；漫江碧透，百舸争流。
鹰击长空，鱼翔浅底，万类霜天竞自由。
怅寥廓，问苍茫大地，谁主沉浮？
携来百侣曾游，忆往昔峥嵘岁月稠。
恰同学少年，风华正茂；书生意气，挥斥方遒。
指点江山，激扬文字，粪土当年万户侯。
曾记否，到中流击水，浪遏飞舟？

* 太行路，白居易，唐
太行之路能摧车，若比人心是坦途。
巫峡之水能覆舟，若比人心是安流。
人心好恶苦不常，好生毛羽恶生疮。
与君结发未五载，岂期牛女为参商。
古称色衰相弃背，当时美人犹怨悔。
何况如今鸾镜中，妾颜未改君心改。
为君熏衣裳，君闻兰麝不馨香。
为君盛容饰， 君看金翠无颜色。
行路难，难重陈。
人生莫作妇人身，百年苦乐由他人。
行路难，难于山，险于水。
不独人间夫与妻，近代君臣亦如此。
君不见左纳言，右纳史，朝承恩，暮赐死。
行路难，不在水，不在山，只在人情反覆间。

* 滕王阁序，唐，王勃
豫章故郡，洪都新府。星分翼轸，地接衡庐。襟三江而带五湖，控蛮荆而引瓯越。物华天宝，龙光射牛斗之墟；人杰地灵，徐孺下陈蕃之榻。雄州雾列，俊采星驰。台隍枕夷夏之交，宾主尽东南之美。都督阎公之雅望，棨戟遥临；宇文新州之懿范，襜帷暂驻。十旬休假，胜友如云；千里逢迎，高朋满座。腾蛟起凤，孟学士之词宗；紫电青霜，王将军之武库。家君作宰，路出名区；童子何知，躬逢胜饯。(豫章故郡 一作：南昌故郡)
时维九月，序属三秋。潦水尽而寒潭清，烟光凝而暮山紫。俨骖騑于上路，访风景于崇阿。临帝子之长洲，得仙人之旧馆。层峦耸翠，上出重霄；飞阁流丹，下临无地。鹤汀凫渚，穷岛屿之萦回；桂殿兰宫，即冈峦之体势。（层峦  一作：层台；即冈 一作：列冈；仙人 一作：天人；飞阁流丹 一作：飞阁翔丹）
披绣闼，俯雕甍，山原旷其盈视，川泽纡其骇瞩。闾阎扑地，钟鸣鼎食之家；舸舰迷津，青雀黄龙之舳。云销雨霁，彩彻区明。落霞与孤鹜齐飞，秋水共长天一色。渔舟唱晚，响穷彭蠡之滨，雁阵惊寒，声断衡阳之浦。(轴 通：舳；迷津 一作：弥津；云销雨霁，彩彻区明 一作：虹销雨霁，彩彻云衢)
遥襟甫畅，逸兴遄飞。爽籁发而清风生，纤歌凝而白云遏。睢园绿竹，气凌彭泽之樽；邺水朱华，光照临川之笔。四美具，二难并。穷睇眄于中天，极娱游于暇日。天高地迥，觉宇宙之无穷；兴尽悲来，识盈虚之有数。望长安于日下，目吴会于云间。地势极而南溟深，天柱高而北辰远。关山难越，谁悲失路之人；萍水相逢，尽是他乡之客。怀帝阍而不见，奉宣室以何年？(遥襟甫畅 一作：遥吟俯畅)
嗟乎！时运不齐，命途多舛。冯唐易老，李广难封。屈贾谊于长沙，非无圣主；窜梁鸿于海曲，岂乏明时？所赖君子见机，达人知命。老当益壮，宁移白首之心？穷且益坚，不坠青云之志。酌贪泉而觉爽，处涸辙以犹欢。北海虽赊，扶摇可接；东隅已逝，桑榆非晚。孟尝高洁，空余报国之情；阮籍猖狂，岂效穷途之哭！(见机 一作：安贫)
勃，三尺微命，一介书生。无路请缨，等终军之弱冠；有怀投笔，慕宗悫之长风。舍簪笏于百龄，奉晨昏于万里。非谢家之宝树，接孟氏之芳邻。他日趋庭，叨陪鲤对；今兹捧袂，喜托龙门。杨意不逢，抚凌云而自惜；钟期既遇，奏流水以何惭？
呜乎！胜地不常，盛筵难再；兰亭已矣，梓泽丘墟。临别赠言，幸承恩于伟饯；登高作赋，是所望于群公。敢竭鄙怀，恭疏短引；一言均赋，四韵俱成。请洒潘江，各倾陆海云尔：
滕王高阁临江渚，佩玉鸣鸾罢歌舞。
画栋朝飞南浦云，珠帘暮卷西山雨。
闲云潭影日悠悠，物换星移几度秋。
阁中帝子今何在？槛外长江空自流。

* 江城子·乙卯正月二十日夜记梦，宋，苏轼
十年生死两茫茫，不思量，自难忘。千里孤坟，无处话凄凉。纵使相逢应不识，尘满面，鬓如霜。

夜来幽梦忽还乡，小轩窗，正梳妆。相顾无言，惟有泪千行。料得年年肠断处，明月夜，短松冈。(肠断 一作：断肠)

* 题龙阳县青草湖，元，唐温如西风吹老洞庭波，一夜湘君白发多。
醉后不知天在水，满船清梦压星河。

* 使至塞上，王维
单车欲问边，属国过居延。
征蓬出汉塞，归雁入胡天。
大漠孤烟直，长河落日圆。
萧关逢候骑，都护在燕然。

* 卜算子·自嘲，清，丁元英
本是后山人，偶做前堂客。
醉舞经阁半卷书，坐井说天阔。
大志戏功名，海斗量福祸。
论到囊中羞涩时，怒指乾坤错。

* 齐庄公出猎，有一虫举，足将搏其轮。问其御曰：“此何虫也？”对曰：“此所谓螳螂者也。其为虫也，知进不知却，不量力而轻敌。”庄公曰：“此为人而，必为天下勇武矣。”回车而避之。

* 君子之交淡如水，小人之交甘若醴

* 真的猛士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。这是怎样的哀痛者和幸福者？然而造化又常常为庸人设计，以时间的流驶，来洗涤旧迹，仅使留下淡红的血色和微漠的悲哀。在这淡红的血色和微漠的悲哀中，又给人暂得偷生，维持着这似人非人的世界。我不知道这样的世界何时是一个尽头！
我们还在这样的世上活着；我也早觉得有写一点东西的必要了。离三月十八日也已有两星期，忘却的救主快要降临了罢，我正有写一点东西的必要了。

* 蜜蜂的刺，一用即丧失了它自己的生命；犬儒〔2〕的刺，一用则苟延了他自己的生命。他们就是如此不同。
约翰穆勒〔3〕说：专制使人们变成冷嘲。而他竟不知道共和使人们变成沉默。
要上战场，莫如做军医；要革命，莫如走后方；要杀人，莫如做刽子手。既英雄，又稳当。
与名流学者谈，对于他之所讲，当装作偶有不懂之处。太不懂被看轻，太懂了被厌恶。偶有不懂之处，彼此最为合宜。
世间大抵只知道指挥刀所以指挥武士，而不想到也可以指挥文人。
又是演讲录，又是演讲录。〔4〕但可惜都没有讲明他何以和先前大两样了；也没有讲明他演讲时，自己是否真相信自己的话。
阔的聪明人种种譬如昨日死。〔5〕不阔的傻子种种实在昨日死。
曾经阔气的要复古，正在阔气的要保持现状，未曾阔气的要革新。 大抵如是。大抵！他们之所谓复古，是回到他们所记得的若干年前，并非虞夏商周。
女人的天性中有母性，有女儿性；无妻性。妻性是逼成的，只是母性和女儿性的混合。
防被欺。自称盗贼的无须防，得其反倒是好人；自称正人君子的必须防，得其反则是盗贼。
楼下一个男人病得要死，那间壁的一家唱着留声机；对面是弄孩子。楼上有两人狂笑；还有打牌声。河中的船上有女人哭着她死去的母亲。人类的悲欢并不相通，我只觉得他们吵闹。
每一个破衣服人走过，叭儿狗就叫起来，其实并非都是狗主人的意旨或使嗾。叭儿狗往往比它的主人更严厉。恐怕有一天总要不准穿破布衫，否则便是共产党。
革命，反革命，不革命。革命的被杀于反革命的。反革命的被杀于革命的。不革命的或当作革命的而被杀于反革命的，或当作反革命的而被杀于革命的，或并不当作什么而被杀于革命的或反革命的。 革命，革革命，革革革命，革革……。
感到寂寞时，会创作；一感到干净时，即无创作，他已经一无所爱。 创作总根于爱。 杨朱无书。 创作虽说抒写自己的心，但总愿意有人看。创作是有社会性的。但有时只要有一个人看便满足：好友，爱人。
人往往憎和尚，憎尼姑，憎回教徒，憎耶教徒，而不憎道士。懂得此理者，懂得中国大半。
要自杀的人，也会怕大海的汪洋，怕夏天死尸的易烂。但遇到澄静的清池，凉爽的秋夜，他往往也自杀了。
凡为当局所“诛”者皆有“罪”。刘邦除秦苛暴，“与父老约，法三章耳。” 而后来仍有族诛，仍禁挟书，还是秦法。〔6）法三章者，话一句耳。
一见短袖子，立刻想到白臂膊，立刻想到全裸体，立刻想到生殖器，立刻想到性交，立刻想到杂交，立刻想到私生子。中国人的想像惟在这一层能够如此跃进。

九月二十四日。


〔1〕本篇最初发表于一九二七年十二月十七日《语丝》周刊第四卷第一期。
（2〕犬儒　原指古希腊昔匿克学派（Cynicism）的哲学家。他们过着禁欲的简陋的生活，被人讥诮为穷犬，所以又称犬儒学派。这些人主张独善其身，以为人应该绝对自由，否定一切伦理道德，以冷嘲热讽的态度看待一切。作者在一九二八年三月八日致章廷谦信中说：“犬儒＝Cynic，它那‘刺’便是‘冷嘲’。”
〔3〕约翰穆勒（J．S．Mill，1806—1873）　英国哲学家、经济学家。
〔4〕这里所说的“演讲录”，指当时不断编印出售的蒋介石、汪精卫、吴稚晖、戴季陶等人的演讲集。作者在写本文后第二天（九月二十五日）致台静农信中说：“现在是大卖戴季陶讲演录了，（蒋介石的也行了一时）。”他们当时在各地发表的演讲，内容和在“四一二”反革命政变以前的演讲很不相同：政变以前，他们不得不口是心非地拥护孙中山联俄、联共、扶助农工的三大政策；改变以后，他们便显露出真实面目，竭力鼓吹反苏、反共、压迫工农。
〔5〕“阔的聪明人种种譬如昨日死”　也是指蒋介石、汪精卫等反革命派。“如昨日死”是引用曾国藩的话：“从前种种如昨日死，从后种种如今日生。”一九二七年八月十八日广州《民国日报》就蒋（介石）汪（精卫）合流反共所发表的一篇社论中，也引用曾国藩的这句话，其中说：“以前种种，譬如昨日死；以后种种，譬如今日生；今后所应负之责任益大且难，这真要我们真诚的不妥协的非投机的同志不念既往而真正联合。”
〔6〕“与父老约，法三章耳”　语见《史记·高祖本纪》：“汉元年（前206）十月，沛公（刘邦）兵遂先诸侯至霸上。……遂西入咸阳……还军霸上。召诸县父老豪杰曰：‘父老苦秦苛法久矣，诽谤者族，偶语者弃市。吾与诸侯约，先入关者王之，吾当王关中。与父老约，法三章耳：杀人者死，伤人及盗抵罪。余悉除去秦法。’”又《汉书·刑法志》载：“汉兴，高祖初入关，约法三章……其后四夷未附，兵革未息，三章之法不足以御奸，于是相国萧何捃摭秦法，取其宜于时者，作律九章。”

* 波伏娃说：“男人的极大幸运在于，他不论在成年还是在小时候，必须踏上一条极为艰苦的道路，不过这是一条最可靠的道路；女人的不幸则在于被几乎不可抗拒的诱惑包围着；她不被要求奋发向上，只被鼓励滑下去到达极乐。当她发觉自己被海市蜃楼愚弄时，已经为时太晚，她的力量在失败的冒险中已被耗尽。”

* 西湖春晓，清，魏宪
十里寒塘路，烟花一半醒。
晨钟催落月，宿火乱稀星。
欹枕看湖白，开窗喜屿青。
笙歌方一歇，莺啭柳洲亭。

* 金缕衣
作者：杜秋娘
劝君莫惜金缕衣，劝君惜取少年时。
花开堪折直须折，莫待无花空折枝。

* 寄黄几复，黄庭坚
我居北海君南海，寄雁传书谢不能。
桃李春风一杯酒，江湖夜雨十年灯。
持家但有四立壁，治病不蕲三折肱。
想见读书头已白，隔溪猿哭瘴溪藤。(想见 一作：想得)

* 茨威格在《断头王后》中写道，“她那时候还太年轻，不知道所有命运赠送的礼物，早已在暗中标好了价格。”

* 寄赠薛涛，元稹，唐
锦江滑腻蛾眉秀，幻出文君与薛涛。
言语巧偷鹦鹉舌，文章分得凤凰毛。
纷纷辞客多停笔，个个公卿欲梦刀。
别后相思隔烟水，菖蒲花发五云高。

* 劝学，荀子
君子曰：学不可以已。
青，取之于蓝，而青于蓝；冰，水为之，而寒于水。木直中绳，輮以为轮，其曲中规。虽有槁暴（pù），不复挺者，輮使之然也。故木受绳则直，金就砺则利，君子博学而日参省乎己，则知明而行无过矣。
故不登高山，不知天之高也；不临深溪，不知地之厚也；不闻先王之遗言，不知学问之大也。干、越、夷、貉之子，生而同声，长而异俗，教使之然也。诗曰：“嗟尔君子，无恒安息。靖共尔位，好是正直。神之听之，介尔景福。”神莫大于化道，福莫长于无祸。
吾尝终日而思矣，不如须臾之所学也；吾尝跂而望矣，不如登高之博见也。登高而招，臂非加长也，而见者远；顺风而呼，声非加疾也，而闻者彰。假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。君子生非异也，善假于物也。(君子生 通：性)
南方有鸟焉，名曰蒙鸠，以羽为巢，而编之以发，系之苇苕，风至苕折，卵破子死。巢非不完也，所系者然也。西方有木焉，名曰射干，茎长四寸，生于高山之上，而临百仞之渊，木茎非能长也，所立者然也。蓬生麻中，不扶而直；白沙在涅，与之俱黑。兰槐之根是为芷，其渐之滫，君子不近，庶人不服。其质非不美也，所渐者然也。故君子居必择乡，游必就士，所以防邪辟而近中正也。
物类之起，必有所始。荣辱之来，必象其德。肉腐出虫，鱼枯生蠹。怠慢忘身，祸灾乃作。强自取柱，柔自取束。邪秽在身，怨之所构。施薪若一，火就燥也，平地若一，水就湿也。草木畴生，禽兽群焉，物各从其类也。是故质的张，而弓矢至焉；林木茂，而斧斤至焉；树成荫，而众鸟息焉。醯酸，而蚋聚焉。故言有招祸也，行有招辱也，君子慎其所立乎！
积土成山，风雨兴焉；积水成渊，蛟龙生焉；积善成德，而神明自得，圣心备焉。故不积跬步，无以至千里；不积小流，无以成江海。骐骥一跃，不能十步；驽马十驾，功在不舍。锲而舍之，朽木不折；锲而不舍，金石可镂。蚓无爪牙之利，筋骨之强，上食埃土，下饮黄泉，用心一也。蟹六跪而二螯，非蛇鳝之穴无可寄托者，用心躁也。
是故无冥冥之志者，无昭昭之明；无惛惛之事者，无赫赫之功。行衢道者不至，事两君者不容。目不能两视而明，耳不能两听而聪。螣蛇无足而飞，鼫鼠五技而穷。《诗》曰：“尸鸠在桑，其子七兮。淑人君子，其仪一兮。其仪一兮，心如结兮！”故君子结于一也。
昔者瓠巴鼓瑟，而流鱼出听；伯牙鼓琴，而六马仰秣。故声无小而不闻，行无隐而不形 。玉在山而草木润，渊生珠而崖不枯。为善不积邪？安有不闻者乎？
学恶乎始？恶乎终？曰：其数则始乎诵经，终乎读礼；其义则始乎为士，终乎为圣人， 真积力久则入，学至乎没而后止也。故学数有终，若其义则不可须臾舍也。为之，人也；舍 之，禽兽也。故书者，政事之纪也；诗者，中声之所止也；礼者，法之大分，类之纲纪也。 故学至乎礼而止矣。夫是之谓道德之极。礼之敬文也，乐之中和也，诗书之博也，春秋之微 也，在天地之间者毕矣。 君子之学也，入乎耳，着乎心，布乎四体，形乎动静。端而言，蝡而动，一可以为法则。小人之学也，入乎耳，出乎口；口耳之间，则四寸耳，曷足以美七尺之躯哉！古之学者为己，今之学者为人。君子之学也，以美其身；小人之学也，以为禽犊。故不问而告谓之傲，问一而告二谓之囋。傲、非也，囋、非也；君子如向矣。
学莫便乎近其人。礼乐法而不说，诗书故而不切，春秋约而不速。方其人之习君子之说，则尊以遍矣，周于世矣。故曰：学莫便乎近其人。
学之经莫速乎好其人，隆礼次之。上不能好其人，下不能隆礼，安特将学杂识志，顺诗书而已耳。则末世穷年，不免为陋儒而已。将原先王，本仁义，则礼正其经纬蹊径也。若挈裘领，诎五指而顿之，顺者不可胜数也。不道礼宪，以诗书为之，譬之犹以指测河也，以戈舂黍也，以锥餐壶也，不可以得之矣。故隆礼，虽未明，法士也；不隆礼，虽察辩，散儒也。
问楛者，勿告也；告楛者，勿问也；说楛者，勿听也。有争气者，勿与辩也。故必由其道至，然后接之；非其道则避之。故礼恭，而后可与言道之方；辞顺，而后可与言道之理；色从而后可与言道之致。故未可与言而言，谓之傲；可与言而不言，谓之隐；不观气色而言，谓瞽。故君子不傲、不隐、不瞽，谨顺其身。诗曰：“匪交匪舒，天子所予。”此之谓也。
百发失一，不足谓善射；千里蹞步不至，不足谓善御；伦类不通，仁义不一，不足谓善学。学也者，固学一之也。一出焉，一入焉，涂巷之人也；其善者少，不善者多，桀纣盗跖也；全之尽之，然后学者也。
君子知夫不全不粹之不足以为美也，故诵数以贯之，思索以通之，为其人以处之，除其害者以持养之。使目非是无欲见也，使耳非是无欲闻也，使口非是无欲言也，使心非是无欲虑也。及至其致好之也，目好之五色，耳好之五声，口好之五味，心利之有天下。是故权利不能倾也，群众不能移也，天下不能荡也。生乎由是，死乎由是，夫是之谓德操。德操然后能定，能定然后能应。能定能应，夫是之谓成人。天见其明，地见其光，君子贵其全也。

译文
君子说：学习不可以停止的。
譬如靛青这种染料是从蓝草里提取的，然而却比蓝草的颜色更青；冰块是冷水凝结而成的，然而却比水更寒冷。木材笔直，合乎墨线，但是(用火萃取）使它弯曲成车轮，（那么）木材的弯度（就）合乎（圆到）如圆规画的一般的标准了，即使又晒干了，（木材）也不会再挺直，用火萃取使它成为这样的。所以木材经墨线比量过就变得笔直，金属制的刀剑拿到磨刀石上去磨就能变得锋利，君子广博地学习，并且每天检验反省自己，那么他就会智慧明理并且行为没有过错了。
因此，不登上高山，就不知天多么高；不面临深涧，就不知道地多么厚；不懂得先代帝王的遗教，就不知道学问的博大。干越夷貉之人，刚生下来啼哭的声音是一样的，而长大后风俗习性却不相同，这是教育使之如此。《诗经》上说：“你这个君子啊，不要总是贪图安逸。恭谨对待你的本职，爱好正直的德行。神明听到这一切，就会赐给你洪福 祥瑞。”精神修养没有比受道德熏陶感染更大了，福分没有比无灾无祸更长远了。
我曾经一天到晚地冥思苦想，（却）比不上片刻学到的知识（收获大）；我曾经踮起脚向远处望，（却）不如登到高处见得广。登到高处招手，手臂并没有加长，可是远处的人却能看见；顺着风喊，声音并没有加大，可是听的人却能听得很清楚。借助车马的人，并不是脚走得快，却可以达到千里之外，借助舟船的人，并不善于游泳，却可以横渡长江黄河。君子的资质秉性跟一般人没什么不同，（只是君子）善于借助外物罢了。
南方有一种叫“蒙鸠”的鸟，用羽毛作窝，还用毛发把窝编结起来，把窝系在嫩芦苇的花穗上，风一吹苇穗折断，鸟窝就坠落了，鸟蛋全部摔烂。不是窝没编好，而是不该系在芦苇上面。西方有种叫“射干”的草，只有四寸高，却能俯瞰百里之遥，不是草能长高，而是因为它长在了高山之巅。蓬草长在麻地里，不用扶持也能挺立住，白沙混进了黑土里，就再不能变白了，兰槐的根叫香艾，一但浸入臭水里，君子下人都会避之不及，不是艾本身不香，而是被浸泡臭了。所以君子居住要选择好的环境，交友要选择有道德的人，才能够防微杜渐保其中庸正直。
事情的发生都是有起因的，荣辱的降临也与德行相应。肉腐了生蛆，鱼枯死了生虫，懈怠疏忽忘记了做人准则就会招祸。太坚硬物体易断裂，太柔弱了又易被束缚，与人不善会惹来怨恨，干柴易燃，低洼易湿，草木丛生，野兽成群，万物皆以类聚。所以靶子设置好了就会射来弓箭，树长成了森林就会引来斧头砍伐，树林繁茂荫凉众鸟就会来投宿，醋变酸了就会惹来蚊虫，所以言语可能招祸，行为可能受辱，君子为人处世不能不保持谨慎。
堆积土石成了高山，风雨就从这里兴起了；汇积水流成为深渊，蛟龙就从这里产生了；积累善行养成高尚的品德，自然会心智澄明，也就具有了圣人的精神境界。所以不积累一步半步的行程，就没有办法达到千里之远；不积累细小的流水，就没有办法汇成江河大海。骏马一跨跃，也不足十步远；劣马拉车走十天，（也能到达，）它的成绩来源于走个不停。（如果）刻几下就停下来了，（那么）腐烂的木头也刻不断。（如果）不停地刻下去，（那么）金石也能雕刻成功。蚯蚓没有锐利的爪子和牙齿，强健的筋骨，却能向上吃到泥土，向下可以喝到土壤里的水，这是由于它用心专一啊。螃蟹有六条腿，两个蟹钳，（但是）如果没有蛇、鳝的洞穴它就无处存身，这是因为它用心浮躁啊。
因此没有刻苦钻研的心志，学习上就不会有显著成绩；没有埋头苦干的实践，事业上就不会有巨大成就。在歧路上行走达不到目的地，同时事奉两个君主的人，两方都 不会容忍他。眼睛不能同时看两样东西而看明白，耳朵不能同时听两种声音而听清楚。螣蛇没有脚但能飞，鼫鼠有五种本领却还是没有办法。《诗》上说：“布谷鸟筑巢在桑树上，它的幼鸟儿有七只。善良的君子们，行为要专一不偏邪。行为专一不偏邪，意志才会如磐石坚。”所以君子的意志坚定专一。
古有瓠巴弹瑟，水中鱼儿也浮出水面倾听，伯牙弹琴，拉车的马会停食仰头而听。所以声音不会因为微弱而不被听见，行为不会因为隐秘而不被发现。宝玉埋在深山，草木就会很润泽，珍珠掉进深渊，崖岸就不会干枯。行善可以积累，哪有积善成德而不被广为传诵的呢？
学习究竟应从何入手又从何结束呢？答：按其途径而言，应该从诵读《诗》、《书》等经典入手到《礼记》结束；就其意义而言，则从做书生入手到成为圣人结束。真诚力行，这样长期积累，必能深入体会到其中的乐趣，学到死方能后已。所以学习的教程虽有尽头，但进取之愿望却不可以有片刻的懈怠。毕生好学才成其为人，反之又与禽兽何异？《尚书》是政事的记录；《诗经》是心声之归结；《礼记》是法制的前提、各种条例的总纲，所以要学到《礼经》才算结束，才算达到了道德之顶峰。《礼经》敬重礼仪，《乐经》讲述中和之声，《诗经》《尚书》博大广阔，《春秋》微言大义，它们已经将天地间的大学问都囊括其中了。
君子学习，是听在耳里，记在心里，表现在威仪的举止和符合礼仪的行动上。一举一动，哪怕是极细微的言行，都可以垂范于人。小人学习是从耳听从嘴出，相距不过四寸而已，怎么能够完美他的七尺之躯呢？古人学习是自身道德修养的需求，现在的人学习则只是为了炫耀于人。君子学习是为了完善自我，小人学习是为了卖弄和哗众取宠，将学问当作家禽、小牛之类的礼物去讨人好评。所以，没人求教你而去教导别人叫做浮躁；问一答二的叫啰嗦；浮躁啰嗦都是不对的，君子答问应象空谷回音一般，不多不少、恰到好处。
学习没有比亲近良师更便捷的了。《礼经》、《乐经》有法度但嫌疏略；《诗经》、《尚书》古朴但不切近现实；《春秋》隐微但不够周详；仿效良师学习君子的学问，既崇高又全面，还可以通达世理。所以说学习没有比亲近良师更便捷的了。
崇敬良师是最便捷的学习途径，其次就是崇尚礼仪了。若上不崇师，下不尚礼，仅读些杂书，解释一下《诗经》《尚书》之类，那么尽其一生也不过是一介浅陋的书生而已。要穷究圣人的智慧，寻求仁义的根本，从礼法入手才是能够融会贯通的捷径。就像弯曲五指提起皮袍的领子，向下一顿，毛就完全顺了。如果不究礼法，仅凭《诗经》《尚书》去立身行事，就如同用手指测量河水，用戈舂黍米，用锥子到饭壶里取东西吃一样，是办不到的。所以，尊崇礼仪，即使对学问不能透彻明了，不失为有道德有修养之士；不尚礼仪，即使明察善辩，也不过是身心散漫无真实修养的浅陋儒生而已。
如果有人前来向你请教不合礼法之事，不要回答；前来诉说不合礼法之事，不要去追问；在你面前谈论不合礼法之事，不要去参与；态度野蛮好争意气的，别与他争辩。所以，一定要是合乎礼义之道的，才给予接待；不合乎礼义之道的，就回避他；因此，对于恭敬有礼的人，才可与之谈道的宗旨；对于言辞和顺的人，才可与之谈道的内容；态度诚恳的，才可与之论及道的精深义蕴。所以，跟不可与之交谈的交谈，那叫做浮躁；跟可与交谈的不谈那叫怠慢；不看对方回应而随便谈话的叫盲目。因此，君子不可浮躁，也不可怠慢，更不可盲目，要谨慎地对待每位前来求教的人。《诗经》说：“不浮躁不怠慢才是天子所赞许的。”说的就是这个道理。
射出的百支箭中有一支不中靶，就不能算是善射；驾驭车马行千里的路程，只差半步而没能走完，这也不能算是善驾；对伦理规范不能融会贯通、对仁义之道不能坚守如一，当然也不能算是善学。学习本是件很需要专心志致的事情，学一阵又停一阵那是市井中的普通人。好的行为少而坏的行为多，桀、纣、拓就是那样的人。能够全面彻底地把握所学的知识，才算得上是个学者。
君子知道学得不全不精就不算是完美，所以诵读群书以求融会贯通，用思考和探索去理解，效仿良师益友来实践，去掉自己错误的习惯性情来保持养护。使眼不是正确的就不想看、耳不是正确的就不想听，嘴不是正确的就不想说，心不是正确的就不愿去思虑。等达到完全醉心于学习的理想境地，就如同眼好五色，耳好五声，嘴好五味那样，心里贪图拥有天下一样。如果做到了这般地步，那么，在权利私欲面前就不会有邪念，人多势众也不会屈服的，天下万物都不能动摇信念。活着是如此，到死也不变。这就叫做有德行、有操守。有德行和操守，才能做到坚定不移，有坚定不移然后才有随机应对。能做到坚定不移和随机应对，那就是成熟完美的人了。到那时天显现出它的光明，大地显现出它的广阔，君子的可贵则在于他德行的完美无缺。

注音
木直中（zhòng)绳
其曲（qu第一声）中（zhòng）规
揉（róu）
槁（gǎo)暴(pù)
就砺（lì）
参（cān通“叁”)省(xǐng)
知（zhì）明
须臾（yú)
跂（qǐ）
假舟楫者 假(jiǎ)
楫（jí）
生（xìng)非异也
跬（kuǐ )步
骐骥（qí jì)
驽（nú)马十驾
锲（qiè)而舍之
金石可镂（lòu)
螯（áo )
蛇鳝（shàn）
朽（xiǔ）
假舆（yú）
善假（jiǎ）于物
朽木不 折（zhé）
爪（zhǎo） 牙

注释
1．君子：指有学问有修养的人。
2．学不可以已：学习不能停止。
3．青取之于蓝：靛青，从蓝草中取得。青，靛青，一种染料。蓝，蓼蓝。蓼（liǎo）蓝：一年生草本植物,茎红紫色，叶子长椭圆形,干时暗蓝色。花淡红色，穗状花序，结瘦果，黑褐色。叶子含蓝汁，可以做蓝色染料。于：从
4．青于蓝：比蓼蓝（更）深。于：比。
5、中绳：（木材）合乎拉直的墨线。木工用拉直的墨线来取直。
6．輮以为轮：輮 ：通“煣”，用火烤使木条弯曲（一种手工艺）。以：把。为：当作。
7．规：圆规，测圆的工具。
8．虽有槁暴：即使又被风吹日晒而干枯了。有，通“又”。槁，枯。暴，同“曝”，晒干。槁暴，枯干。
9．挺：直。
10．受绳：用墨线量过。
11．金：指金属制的刀剑等。
12．就砺：拿到磨刀石上去磨。砺，磨刀石。就，动词，接近，靠近。
13．君子博学而日参省乎己，则知明而行无过矣：参省乎己：对自己检查、省察。参，一译检验，检查；二译同“叁”，多次。省，省察。乎，介词，于。博学：广泛地学习。日：每天。知：通“智”，智慧。明：明达。行无过：行动没有过错。
14．吾尝终日而思矣：而，表修饰
15．须臾：片刻，一会儿。
16．跂：提起脚后跟。
17．博见：看见的范围广，见得广。
18．而见者远：意思是远处的人也能看见。而，表转折。
19．疾：快，速，这里引申为“洪亮”，指声音宏大。
20．彰：清楚。
21．假：借助，利用。舆：车。
22．利足：脚走得快。致：达到。
23．水：指游泳。名词，用作动词。
24．绝：横渡。
25．生非异：本性（同一般人）没有差别。生，通“性”，资质，禀赋。
26．善假于物也：于：向。物：外物，指各种客观条件。
27．兴：起,兴盛。
28．焉：于之，在那里。
29．渊：深水。
30．蛟：一种似龙的生物。
31．积善成德，而神明自得，圣心备焉：积累善行而养成品德，达到很高的境界，通明的思想（也就）具备了。得，获得。而，表因果关系。
32．跬：古代的半步。古代称跨出一脚为“跬”，跨两脚为“步”。
33．无以：没有用来……的（办法）
34．骐骥：骏马，千里马。
35．驽马十驾：劣马拉车连走十天，（也能走得很远。）驽马，劣马。驾，马拉车一天所走的路程叫“一驾”。
36．功在不舍：（它的）成功在于不停止。舍，停。
37．锲：用刀雕刻。
38．金石可镂：金：金属。石：石头。镂：原指在金属上雕刻，泛指雕刻。
39．用心一也：（这是）因为用心专一（的缘故）。用，以，因为。
40．六跪：六条腿，蟹实际上是八条腿。跪，蟹脚。（一说，海蟹后面的两条腿只能划水，不能用来走路或自卫，所以不能算在“跪”里。另一说，“六”虚指。这两说高中课本中没有提到）
41．螯：螃蟹的大钳子。
42．躁：浮躁，不专心。
43．神明：精神智慧。
44．跪：脚，蟹腿。▲

* 从军行，王昌龄
青海长云暗雪山，孤城遥望玉门关。
黄沙百战穿金甲，不破楼兰终不还。

* 别子才司令，方岳
不如意事常八九，
可与人言无二三。
自识荆门子才甫，
梦驰铁马战城南。

* 孟子·告天下
舜发于畎亩之中，傅说举于版筑之间，胶鬲举于鱼盐之中，管夷吾举于士，孙叔敖举于海，百里奚举于市。
故天将降大任于斯人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为，所以动心忍性，曾益其所不能。
人恒过，然后能改:困于心，衡于虑，而后作；徵于色，发于声，而后喻。入则无法家拂士，出则无敌国外患者，国恒亡。然后知生于忧患而死于安乐也。

* 报任少卿书 / 报任安书
汉 · 司马迁
太史公牛马走司马迁再拜言。
少卿足下：曩者辱赐书，教以慎于接物，推贤进士为务。意气勤勤恳恳，若望仆不相师，而用流俗人之言，仆非敢如此也。请略陈固陋。阙然久不报，幸勿为过。
仆之先人非有剖符丹书之功，文史星历，近乎卜祝之间，固主上所戏弄，倡优所畜，流俗之所轻也。假令仆伏法受诛，若九牛亡一毛，与蝼蚁何以异？而世又不与能死节者比，特以为智穷罪极，不能自免，卒就死耳。何也？素所自树立使然。人固有一死，或重于泰山，或轻于鸿毛，用之所趋异也。太上不辱先，其次不辱身，其次不辱理色，其次不辱辞令，其次诎体受辱，其次易服受辱，其次关木索、被箠楚受辱，其次剔毛发、婴金铁受辱，其次毁肌肤、断肢体受辱，最下腐刑极矣！传曰：“刑不上大夫。”此言士节不可不勉励也。猛虎在深山，百兽震恐，及在槛阱之中，摇尾而求食，积威约之渐也。故士有画地为牢，势不可入；削木为吏，议不可对，定计于鲜也。今交手足，受木索，暴肌肤，受榜箠，幽于圜墙之中。当此之时，见狱吏则头枪地，视徒隶则心惕息。何者？积威约之势也。及以至是，言不辱者，所谓强颜耳，曷足贵乎！且西伯，伯也，拘于羑里；李斯，相也，具于五刑；淮阴，王也，受械于陈；彭越、张敖，南向称孤，系狱具罪；绛侯诛诸吕，权倾五伯，囚于请室；魏其，大将也，衣赭衣、关三木；季布为朱家钳奴；灌夫受辱于居室。此人皆身至王侯将相，声闻邻国，及罪至罔加，不能引决自裁，在尘埃之中。古今一体，安在其不辱也？由此言之，勇怯，势也；强弱，形也。审矣，何足怪乎？夫人不能早自裁绳墨之外，以稍陵迟，至于鞭箠之间，乃欲引节，斯不亦远乎！古人所以重施刑于大夫者，殆为此也。
夫人情莫不贪生恶死，念父母，顾妻子；至激于义理者不然，乃有所不得已也。今仆不幸，早失父母，无兄弟之亲，独身孤立，少卿视仆于妻子何如哉？且勇者不必死节，怯夫慕义，何处不勉焉！仆虽怯懦，欲苟活，亦颇识去就之分矣，何至自沉溺缧绁之辱哉！且夫臧获婢妾，犹能引决，况若仆之不得已乎？所以隐忍苟活，幽于粪土之中而不辞者，恨私心有所不尽，鄙陋没世，而文采不表于后也。
古者富贵而名摩灭，不可胜记，唯倜傥非常之人称焉。盖文王拘而演《周易》；仲尼厄而作《春秋》；屈原放逐，乃赋《离骚》；左丘失明，厥有《国语》；孙子膑脚，《兵法》修列；不韦迁蜀，世传《吕览》；韩非囚秦，《说难》《孤愤》；《诗》三百篇，此皆圣贤发愤之所为作也。此人皆意有所郁结，不得通其道，故述往事、思来者。乃如左丘无目，孙子断足，终不可用，退而论书策以舒其愤，思垂空文以自见。
仆窃不逊，近自托于无能之辞，网罗天下放失旧闻，略考其行事，综其终始，稽其成败兴坏之纪，上计轩辕，下至于兹，为十表，本纪十二，书八章，世家三十，列传七十，凡百三十篇。亦欲以究天人之际，通古今之变，成一家之言。草创未就，会遭此祸，惜其不成，是以就极刑而无愠色。仆诚以著此书，藏之名山，传之其人，通邑大都，则仆偿前辱之责，虽万被戮，岂有悔哉？然此可为智者道，难为俗人言也！
且负下未易居，下流多谤议。仆以口语遇遭此祸，重为乡党所笑，以污辱先人，亦何面目复上父母之丘墓乎？虽累百世，垢弥甚耳！是以肠一日而九回，居则忽忽若有所亡，出则不知其所如往。每念斯耻，汗未尝不发背沾衣也。身直为闺阁之臣，宁得自引深藏于岩穴邪！故且从俗浮沉，与时俯仰，以通其狂惑。今少卿乃教之以推贤进士，无乃与仆之私心剌谬乎？今虽欲自雕琢，曼辞以自饰，无益，于俗不信，适足取辱耳。要之死日，然后是非乃定。书不能悉意，故略陈固陋。

* 七绝·改西乡隆盛诗赠父亲
1909年 毛泽东
孩儿立志出乡关，
学不成名誓不还。
埋骨何须桑梓地，
人生无处不青山！
原诗
男儿立志出乡关，
学不成名死不还。
埋骨何须桑梓地，
人生无处不青山。
——西乡隆盛

* 念奴娇·登多景楼
危楼还望，叹此意、今古几人曾会？鬼设神施，浑认作、天限南疆北界。一水横陈，连岗三面，做出争雄势。六朝何事，只成门户私计？
因笑王谢诸人，登高怀远，也学英雄涕。凭却长江，管不到，河洛腥膻无际。正好长驱，不须反顾，寻取中流誓。小儿破贼，势成宁问强对！(强对 一作：疆场)

* 忆秦娥·娄山关
西风烈，
长空雁叫霜晨月。
霜晨月，
马蹄声碎，
喇叭声咽。

雄关漫道真如铁，
而今迈步从头越。
从头越，
苍山如海，
残阳如血。

* 沁园春·雪
北国风光，千里冰封，万里雪飘。
望长城内外，惟余莽莽；大河上下，顿失滔滔。(余 通：馀)
山舞银蛇，原驰蜡象，欲与天公试比高。(原驰 原作：原驱)
须晴日，看红装素裹，分外妖娆。(红装 一作：银装)
江山如此多娇，引无数英雄竞折腰。
惜秦皇汉武，略输文采；唐宗宋祖，稍逊风骚。
一代天骄，成吉思汗，只识弯弓射大雕。
俱往矣，数风流人物，还看今朝。

* 桃花庵歌，唐寅
桃花坞里桃花庵，桃花庵下桃花仙。
桃花仙人种桃树，又摘桃花换酒钱。
酒醒只在花前坐，酒醉还来花下眠。
半醒半醉日复日，花落花开年复年。
但愿老死花酒间，不愿鞠躬车马前。
车尘马足富者趣，酒盏花枝贫者缘。
若将富贵比贫贱，一在平地一在天。
若将贫贱比车马，他得驱驰我得闲。
别人笑我太疯癫，我笑他人看不穿。
不见五陵豪杰墓，无花无酒锄作田。

* 剑客，唐，贾岛
十年磨一剑， 霜刃未曾试。
今日把示君， 谁有不平事？

* 少年行四首，唐，王维
【其一】
新丰美酒斗十千，咸阳游侠多少年。
相逢意气为君饮，系马高楼垂柳边。
【其二】
出身仕汉羽林郎，初随骠骑战渔阳。
孰知不向边庭苦，纵死犹闻侠骨香。
【其三】
一身能擘两雕弧，虏骑千重只似无。
偏坐金鞍调白羽，纷纷射杀五单于。
【其四】
汉家君臣欢宴终，高议云台论战功。
天子临轩赐侯印，将军佩出明光宫。

* 赠郭将军，唐，李白
将军少年出武威，入掌银台护紫微。
平明拂剑朝天去，薄暮垂鞭醉酒归。
爱子临风吹玉笛，美人向月舞罗衣。
畴昔雄豪如梦里，相逢且欲醉春晖。

* 和张仆射塞下曲六首，唐，卢纶
其二
林暗草惊风，将军夜引弓。
平明寻白羽，没在石棱中。
其三
月黑雁飞高，单于夜遁逃。
欲将轻骑逐，大雪满弓刀。

* 塞下曲六首，唐，李白
五月天山雪，无花只有寒。
笛中闻折柳，春色未曾看。
晓战随金鼓，宵眠抱玉鞍。
愿将腰下剑，直为斩楼兰。

137纪念刘和珍君，鲁迅
一
中华民国十五年三月二十五日，就是国立北京女子师范大学为十八日在段祺瑞执政府前遇害的刘和珍杨德群两君开追悼会的那一天，我独在礼堂外徘徊，遇见程君，前来问我道，“先生可曾为刘和珍写了一点什么没有？”我说“没有”。她就正告我，“先生还是写一点罢；刘和珍生前就很爱看先生的文章。”
这是我知道的，凡我所编辑的期刊，大概是因为往往有始无终之故罢，销行一向就甚为寥落，然而在这样的生活艰难中，毅然预定了《莽原》全年的就有她。我也早觉得有写一点东西的必要了，这虽然于死者毫不相干，但在生者，却大抵只能如此而已。倘使我能够相信真有所谓“在天之灵”，那自然可以得到更大的安慰，——但是，现在，却只能如此而已。
可是我实在无话可说。我只觉得所住的并非人间。四十多个青年的血，洋溢在我的周围，使我难于呼吸视听，那里还能有什么言语？长歌当哭，是必须在痛定之后的。而此后几个所谓学者文人的阴险的论调，尤使我觉得悲哀。我已经出离愤怒了。我将深味这非人间的浓黑的悲凉；以我的最大哀痛显示于非人间，使它们快意于我的苦痛，就将这作为后死者的菲薄的祭品，奉献于逝者的灵前。
二
真的猛士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。这是怎样的哀痛者和幸福者？然而造化又常常为庸人设计，以时间的流驶，来洗涤旧迹，仅使留下淡红的血色和微漠的悲哀。在这淡红的血色和微漠的悲哀中，又给人暂得偷生，维持着这似人非人的世界。我不知道这样的世界何时是一个尽头！
我们还在这样的世上活着；我也早觉得有写一点东西的必要了。离三月十八日也已有两星期，忘却的救主快要降临了罢，我正有写一点东西的必要了。
三
在四十余被害的青年之中，刘和珍君是我的学生。学生云者，我向来这样想，这样说，现在却觉得有些踌躇了，我应该对她奉献我的悲哀与尊敬。她不是“苟活到现在的我”的学生，是为了中国而死的中国的青年。
她的姓名第一次为我所见，是在去年夏初杨荫榆女士做女子师范大学校长，开除校中六个学生自治会职员的时候。其中的一个就是她；但是我不认识。直到后来，也许已经是刘百昭率领男女武将，强拖出校之后了，才有人指着一个学生告诉我，说：这就是刘和珍。其时我才能将姓名和实体联合起来，心中却暗自诧异。我平素想，能够不为势利所屈，反抗一广有羽翼的校长的学生，无论如何，总该是有些桀骜锋利的，但她却常常微笑着，态度很温和。待到偏安于宗帽胡同，赁屋授课之后，她才始来听我的讲义，于是见面的回数就较多了，也还是始终微笑着，态度很温和。待到学校恢复旧观，往日的教职员以为责任已尽，准备陆续引退的时候，我才见她虑及母校前途，黯然至于泣下。此后似乎就不相见。总之，在我的记忆上，那一次就是永别了。
四
我在十八日早晨，才知道上午有群众向执政府请愿的事；下午便得到噩耗，说卫队居然开枪，死伤至数百人，而刘和珍君即在遇害者之列。但我对于这些传说，竟至于颇为怀疑。我向来是不惮以最坏的恶意，来推测中国人的，然而我还不料，也不信竟会下劣凶残到这地步。况且始终微笑着的和蔼的刘和珍君，更何至于无端在府门前喋血呢？
然而即日证明是事实了，作证的便是她自己的尸骸。还有一具，是杨德群君的。而且又证明着这不但是杀害，简直是虐杀，因为身体上还有棍棒的伤痕。
但段政府就有令，说她们是“暴徒”！
但接着就有流言，说她们是受人利用的。
惨象，已使我目不忍视了；流言，尤使我耳不忍闻。我还有什么话可说呢？我懂得衰亡民族之所以默无声息的缘由了。沉默呵，沉默呵！不在沉默中爆发，就在沉默中灭亡。
五
但是，我还有要说的话。
我没有亲见；听说她，刘和珍君，那时是欣然前往的。自然，请愿而已，稍有人心者，谁也不会料到有这样的罗网。但竟在执政府前中弹了，从背部入，斜穿心肺，已是致命的创伤，只是没有便死。同去的张静淑君想扶起她，中了四弹，其一是手枪，立仆；同去的杨德群君又想去扶起她，也被击，弹从左肩入，穿胸偏右出，也立仆。但她还能坐起来，一个兵在她头部及胸部猛击两棍，于是死掉了。
始终微笑的和蔼的刘和珍君确是死掉了，这是真的，有她自己的尸骸为证；沉勇而友爱的杨德群君也死掉了，有她自己的尸骸为证；只有一样沉勇而友爱的张静淑君还在医院里呻吟。当三个女子从容地转辗于文明人所发明的枪弹的攒射中的时候，这是怎样的一个惊心动魄的伟大呵！中国军人的屠戮妇婴的伟绩，八国联军的惩创学生的武功，不幸全被这几缕血痕抹杀了。
但是中外的杀人者却居然昂起头来，不知道个个脸上有着血污……
六
时间永是流驶，街市依旧太平，有限的几个生命，在中国是不算什么的，至多，不过供无恶意的闲人以饭后的谈资，或者给有恶意的闲人作“流言”的种子。至于此外的深的意义，我总觉得很寥寥，因为这实在不过是徒手的请愿。人类的血战前行的历史，正如煤的形成，当时用大量的木材，结果却只是一小块，但请愿是不在其中的，更何况是徒手。
然而既然有了血痕了，当然不觉要扩大。至少，也当浸渍了亲族；师友，爱人的心，纵使时光流驶，洗成绯红，也会在微漠的悲哀中永存微笑的和蔼的旧影。陶潜说过，“亲戚或余悲，他人亦已歌，死去何所道，托体同山阿。”倘能如此，这也就够了。
七
我已经说过：我向来是不惮以最坏的恶意来推测中国人的。但这回却很有几点出于我的意外。一是当局者竟会这样地凶残，一是流言家竟至如此之下劣，一是中国的女性临难竟能如是之从容。
我目睹中国女子的办事，是始于去年的，虽然是少数，但看那干练坚决，百折不回的气概，曾经屡次为之感叹。至于这一回在弹雨中互相救助，虽殒身不恤的事实，则更足为中国女子的勇毅，虽遭阴谋秘计，压抑至数千年，而终于没有消亡的明证了。倘要寻求这一次死伤者对于将来的意义，意义就在此罢。
苟活者在淡红的血色中，会依稀看见微茫的希望；真的猛士，将更奋然而前行。
呜呼，我说不出话，但以此记念刘和珍君！
四月一日
发表于一九二六年四月十二日《故事会》周刊第七十四期

* 《明史·成祖本纪》：文皇少长习兵，据幽燕形胜之地，乘建文孱弱，长驱内向，奄有四海。即位以后，躬行节俭，水旱朝告夕振，无有壅蔽。知人善任，表里洞达，雄武之略，同符高祖。六师屡出，漠北尘清。至其季年，威德遐被，四方宾服，明命而入贡者殆三十国。幅陨之广，远迈汉、唐。成功骏烈，卓乎盛矣。然而革除之际，倒行逆施，惭德亦曷可掩哉。

* 备住荆州数年，尝於表坐起至厕，见髀里肉生，慨然流涕。还坐，表怪问备，备曰：“吾常身不离鞍，髀肉皆消。今不复骑，髀里肉生。日月若驰，老将至矣，而功业不建，是以悲耳”
* 然折而不挠，终不为下者
* 贺新郎·同父见和再用韵答之，宋，辛弃疾
老大那堪说。似而今、元龙臭味，孟公瓜葛。我病君来高歌饮，惊散楼头飞雪。笑富贵千钧如发。硬语盘空谁来听？记当时、只有西窗月。重进酒，换鸣瑟。
事无两样人心别。问渠侬：神州毕竟，几番离合？汗血盐车无人顾，千里空收骏骨。正目断关河路绝。我最怜君中宵舞，道“男儿到死心如铁”。看试手，补天裂。
* 水浒人物-宋江,明,施耐庵
心在山东身在吴， 飘蓬江海漫嗟吁。
他时若遂凌云志， 敢笑黄巢不丈夫。 ​
* 北大红楼两巨人，纷传北李与南陈。孤松独秀如椽笔，日月双悬照古今。北李南陈，两大星辰；茫茫黑夜，吾辈仰辰。
* 七律·长征
毛泽东
红军不怕远征难，
万水千山只等闲。
五岭逶迤腾细浪，
乌蒙磅礴走泥丸。
金沙水拍云崖暖，
大渡桥横铁索寒。
更喜岷山千里雪，
三军过后尽开颜。
* 疾风知劲草，板荡识诚臣。
* 拔剑舞中庭，
浩歌振林峦！
丈夫意如此，
不学腐儒酸！

* 水调歌头·落日古城角
宋 · 辛弃疾
落日古城角，把酒劝君留。长安路远，何事风雪敝貂裘。散尽黄金身世，不管秦楼人怨，归计狎沙鸥。明夜扁舟去，和月载离愁。
功名事，身未老，几时休。诗书万卷，致身须到古伊周。莫学班超投笔，纵得封侯万里，憔悴老边州。何处依刘客，寂寞赋登楼。

* 过零丁洋，文天祥
辛苦遭逢起一经，干戈寥落四周星。
山河破碎风飘絮，身世浮沉雨打萍。
惶恐滩头说惶恐，零丁洋里叹零丁。
人生自古谁无死？留取丹心照汗青。

* 如果你第一次没有成功，那就从新定义成功是什么。——佚名

* 即使对邪恶从侧面进行上千次攻击，也比不上从根源上进行一次攻击。

* 乘法令人恼怒，除法更甚；比例运算困扰着我，做练习令我发疯。

* 知难而进，志在必成！

* 《增广贤文》:忍得一时之气，免得百日之忧。近来学得乌龟法，得缩头时且缩头。
为人学得乌龟法，得缩头时且缩头。

* 入都，李鸿章，清
【其一】
丈夫只手把吴钩，意气高于百尺楼。
一万年来谁著史，三千里外欲封侯。
定将捷足随途骥，那有闲情逐水鸥。
笑指泸沟桥畔月，几人从此到瀛洲？

* 讨袁檄文，孙中山
壬子之五[二]月，国民悯构兵之惨，许清室旧臣自新，竭诚志以临时政府付袁世凯，四海之内，莫不走相告曰：息兵安民，以事建设，是大仁大义举也。吾民既竭诚以望袁，今袁所报民者何如哉？辛亥之役，深[流]血万里，人尽好生，何为而然？若知袁种之暴戾更甚于清，则又何苦膏血万户，以博一人皇帝之雄哉！所以宁死而不悔者，誓与共和相始长耳。
今袁背弃前盟，暴行帝制，解散自治会，而闾阎无安民矣；解散国会，而国家无正论矣；滥用公款，谋杀人才，而陷国家于危险之地位矣；假民党狱，而良懦多为无辜矣。有此四者，国无不亡！国亡则民奴，独袁与二三附从之奸，尚可执挺衔璧以保富贵耳。呜呼！吾民何不幸，而委此国家生命于袁氏哉！自袁为总统，野有饿莩，而都下之笙歌不彻；国多忧患，而效[郊]祀之典礼未忘。万户涕泪，一人冠冕，其心尚有“共和”二字存耶？既妄[忘]共和，即称民贼。吾侪昔以大仁大义铸此巨错，又焉敢不犯难，誓死戮此民贼，以拯吾民。
今长江大河，万里以内，武汉京津，扼要诸军，皆已暗受旗帜，磨剑以待。一旦义旗起，呼声动天地。当以秦陇一军，出关北指；川楚一军，规画中原；闽粤旌旗横海，合齐鲁以捣京左。三军既兴，我将与诸君子扼扬子江口，定苏浙，以树东南之威。掣庭扫穴，共戮国贼，期可指日待焉。书曰：“民惟邦本，本固邦宁。”又曰：“纣有臣亿万，惟亿万心。予有臣三千，惟一心。”正义所至，何坚不破？愿与爱国之豪俊共图之！

*
胡公治史可谓严矣。公尝著《通鉴地理考》百卷，尚未付印，偶读王伯厚之《通鉴地理通释》，竟以为己赘，辄尽焚原稿，不传于后世。惜乎哉！何自苛若是？
近人治史，尤擅考据。盖因明清以降，思想钳固，时人既有心得，然其文逮之者鲜矣。故每寄志于史，凡考据必求僻好偏，以自保诸上而夸于下者，遂逐末道。其较梅涧公，则形似而神离，去之远矣。
且自司马温公后，官吏叵信。其若《明史》，凡涉满清，皆曲笔以附鞑虏。崔杼之流，何止上古？凡今曰圣，尊讳权掩。史家本色，了然无存，岂不谬哉？
逮至民国，西学东渐，风格蔚然一新，巨匠辈出。然青秽并存，一时唯洋诺诺，数典忘祖，殆祸及今。已而多事之秋，传承几覆。嗟乎！儒道之式微者久矣。今之众人，髫龀不闻《诗》、《书》、《礼》、《易》，弱冠方觉文华可惜。螽斯振振，毋污先圣，虽累百世，垢弥甚而。蝼蚁奋力，不能妄推中兴；余烬犹存，惟愿其传承不断于吾辈。
* 阿维·阿斯平纳尔的闹钟
近年来，一家报纸刊载了一段新闻，说是有个警官在一个下雨天的清早4点钟的时候，在格兰德尔兄弟工厂大门口阶石上，发现一个小男孩在睡觉。他把孩子弄醒了，盘问他的究竟。
小家伙解释说他就在那儿干活，他害怕迟到，他是每天清晨六点钟上工的，他听说那时候才不过四点钟，显然感到很惊奇。警官检查了这个吓昏了的小孩手里的一个小包。里面有一条干净的工作围裙和三片涂着糖浆的面包。
孩子进一步解释说，他醒来时，以为时间已经迟了，他不想叫醒母亲问她是什么时候了，"因为她洗了一整天的衣服"。他也没有看钟，因为他们家"没有钟"。他没有自动说明一下，既然家里没有钟，他又怎能盼望他母亲知道是什么时候呢。但是，也许，就像他那一类的小家伙一样，他对于母亲无边的智慧，是有着无限的信心。他的名字叫阿维·阿斯平纳尔，先生，他住在琼司胡同。爸爸已经故世了。
几天以后，这一家报纸很有趣地报道说，关于本报前所刊载的感人事件，已有一位慈善的社会名媛在她的朋友之间发起募捐，以便给那个被人发现在格兰德尔兄弟厂房门口睡觉的小男孩子购置闹钟一只云云。
以后，关于这感人的事件，报纸又曾提到，说是闹钟已经购妥，并且交给了孩子的妈妈，她似乎感激涕零云云。同时另一方面的消息却又说，上面所说的话是颇为言过其实的。
这件感人的事件终于以下面这段消息告结束。这段消息使人毫不置疑地知道，这位慈善的杜交名媛原来不是别人，正是厂主格兰德尔家的一位美丽动人而又多才多艺的小姐。
复活节假期中，阿维·阿斯平纳尔一直伤风很厉害，睡倒在床上，现在已经是假期最后一天的时间了。照他自己的话说，他仍然有点"闹嗓子"，时候已经是差不多9点钟了，琼司胡同的生意正闹得欢畅哩。
"好多了，妈，我好多了，"阿维说，"我喝的白糖醋水把痰给化了，那要命的咳嗽就给赶出来了。"歇不多久，而咳嗽就"赶出来"了，弄得他连话也说不出。他喘过一口气之后，就说：
"不管好歹，我明天非去上工不可。妈，把闹钟给我。"
"我跟你说你不能去。去了会送命的！"
"说了也没有用，妈，我们不能等着饿死--再说--万一有人替了我的差事呢！妈，把钟给我吧。"
"我待会儿差一个小孩子替你去说你病了，他们一定会让你歇一两天的。"
"那没有用，他们不肯等我的，我知道他们--格兰德尔兄弟公司才不管我病不病呢！放心吧，妈，我将来总要有一天比他们都强。把闹钟给我，妈妈。"
她把闹钟递给他，他赶着把发条上紧，对准了闹钟。"铃铛有毛病了，"他咕哝着说，"它已经一连有两个晚上打错了时间。可是我这还是试一试吧。我让他在五点钟闹，这样一来我就有时间穿衣服了，还可以早到一会儿呢。唉，就愿我不必走那么远的路就好了。"
他停下来，念刻在钟面上的一圈字：
睡得早，起得早
使人聪明、富贵、身体好。
他以前念这两句诗念了许多次了，很喜欢它的韵律。他曾经一遍又一遍地暗暗背诵它，但从没有去想一想它所包含的意义或哲理。他以前做梦也没有想到去怀疑任何印出来的字--何况这是刻在钟面上的呢。可是现在似乎有点恍然大悟了。他把这句话思索了一会儿，接着又一次把它大声念出来。最后，他一语不发地在心中翻来覆去思量着。
"妈！"他忽然说，"我认为这是蒙人的！"她把钟拿了过来，放在架子上，把阿维睡的沙发上的小被窝盖严，吹熄了灯。
阿维似乎唾着了。可是她却睡不着，醒着躺在那儿想自己的愁苦事。
她想到自己的一天早上死在工厂，被人抬了回来的丈夫，想到自己的只有在不用蹲监狱时候才回家来吃闲饭的大儿子；想到她的二儿子，他已经在别的城市里给自己安下了舒服的家，再也不来过问她：又想到老三--可怜的、瘦弱的小阿维--他像一个大人似地挣扎着来帮助家里，在他这个年纪本应该上学念书的，现在却不得不在格兰德尔兄弟工厂里消耗着他年轻的生命。她想到在隔壁屋里的那5个不顶事的小娃娃，想到自己的苦日子--从早上5点半给人擦地板直擦到8点钟，然后才开始干一天的活--给人洗衣服！--她又想到不得不在妓院的包围中把孩子抚养成人，只为的是没有钱，付不起更高的房租，搬不起家；接着她又想到房租。
阿维在睡梦中讲起话来。
"你睡不着吧，阿维？"她问，"你嗓子痛不痛？要什么吗？"
"我想睡，"他迷迷糊糊地嘟囔说，"可是好像再过一会儿就要……就要……"。
"就要怎么样，阿维？"她急忙问，深怕他说起胡话来。
"就要响铃铛了。"
他是在说梦话呢。
她轻轻站起来，把闹钟往后拨了两个钟点。"现在他可以好好休息了。"她轻轻地自言自语说。
过了不－会儿，阿维忽然直挺挺坐起来，匆匆地说，"妈，我想闹钟刚才响了！"然后，也不等回答，他又突然躺下去睡。
雨停了，明亮的、满缀着星辰的苍穹覆盖着海洋和城市，不分彼此地覆盖着贫民窟与富丽的别墅；可是从琼司胡同中的这一家破房子里，除了南十字星座和它周围的几颗星星外。再看不见更大的一块苍天。从格兰德尔家的宅地--所谓"格兰德尔别墅"--看来，这便是贵妇名媛所说的"可爱的夜晚了"。在格兰德尔别墅，逶迤地通到水边的花园以及露台上，都洒遍了月光，它的窗户因为举行复活节舞会而灯火辉煌，它的多少大厅挤满了最尊贵的社交圈中的人物，其中有一位美丽动人而又多才多艺的小姐正在孕育一篇关于一个小清道夫的悲惨故事，赚得一群高等人士的不少热泪。
闹钟确是有毛病了，不然就是阿斯平纳尔太太拨错了，因为在夜深入静的时候，铃声忽然震人地响了起来。她痛苦地一惊而醒，静静地躺着，想阿维一定要起来了；可是他却没有动静。她把惨白的、惊恐的脸转向阿维所睡的沙发--琼司胡同的孤伶伶的街灯从高过窗子的人行道上把灯光照进了窗子，借着灯光她看见孩子没有动弹。
为什么闹钟吵不醒他，他平常睡得多不沉实呀！"阿维！"她叫道，没有回答。"阿维！"她又叫，在她恐惧的声音里还搀杂着一种奇特的责备的声调。阿维根本不回答。
"唉！我的天哪！"她呻吟道。
她起来，站在沙发旁。阿维仰面躺着；双臂交叉在胸口--这是他最喜欢的睡觉的姿势；可是他却睁大了眼，直直地朝上瞪着，好像他要透过天花板和房顶，要瞧瞧上帝应该在的地方。
他已经死了。
"我的天哪！我的天哪！"她哭了。

* 七律·到韶山，毛泽东
别梦依稀咒逝川，故园三十二年前。
红旗卷起农奴戟，黑手高悬霸主鞭。
为有牺牲多壮志，敢教日月换新天。
喜看稻菽千重浪，遍地英雄下夕烟。

* 示儿，陆游
死去元知万事空，但悲不见九州同。王师北定中原日，家祭无忘告乃翁。

* 无题，周恩来
大江歌罢掉头东，邃密群科济世穷。
面壁十年图破壁，难酬蹈海亦英雄。

* 1940年5月1日，张自忠亲笔昭告各部队、各将领：“国家到了如此地步，除我等为其死，毫无其他办法。更相信，只要我等能本此决心，我们国家及我五千年历史之民族，决不至亡于区区三岛倭奴之手。为国家民族死之决心，海不清，石不烂，决不半点改变。”

* 蟑螂这种世界上最古老的有翅昆虫早在《旧约》时代就已经成为人们用拖鞋击打的重点对象，但这一物种凭借顽强的生命力战胜了从蘸硼砂的番茄片到拌糖的面粉等一切杀灭方式，以其一千六百零三个变种抵抗住人类最古老、最执着也最残酷的迫害，人类自起源以来对其他物种包括自身在内都没有施展过这样的手段，故而杀灭蟑螂可称为人类除繁衍后代之后更明确、更迫切的本能，而蟑螂之所以能逃过人类凶狠的捕杀，只是因为它们成功地躲入黑暗，利用了人类与生俱来对黑暗的恐惧，但同时它们也变得对正午的阳光十分敏感，故此，无论在中世纪、在如今还是在将来的世代，有效杀灭蟑螂的方式唯有光照而已。
* 泊秦淮，杜牧
烟笼寒水月笼沙，夜泊秦淮近酒家。
商女不知亡国恨，隔江犹唱后庭花。
* 送杜少府之任蜀州，王勃
城阙辅三秦，风烟望五津。
与君离别意，同是宦游人。
海内存知己，天涯若比邻。
无为在歧路，儿女共沾巾。

* 西江月·世事一场大梦，苏轼
世事一场大梦，人生几度秋凉？夜来风叶已鸣廊。看取眉头鬓上。
酒贱常愁客少，月明多被云妨。中秋谁与共孤光。把盏凄然北望。

* 山中与幽人对酌，李白
两人对酌山花开，一杯一杯复一杯。
我醉欲眠卿且去，明朝有意抱琴来。
* 送陈章甫，李颀，唐
四月南风大麦黄，枣花未落桐阴长。(阴 一作：叶)
青山朝别暮还见，嘶马出门思旧乡。
陈侯立身何坦荡，虬须虎眉仍大颡。
腹中贮书一万卷，不肯低头在草莽。
东门酤酒饮我曹，心轻万事如鸿毛。
醉卧不知白日暮，有时空望孤云高。
长河浪头连天黑，津口停舟渡不得。
郑国游人未及家，洛阳行子空叹息。
闻道故林相识多，罢官昨日今如何。
* 死水，闻一多
这是一沟绝望的死水，
清风吹不起半点漪沦。
不如多扔些破铜烂铁，
爽性泼你的剩菜残羹。

也许铜的要绿成翡翠，
铁罐上绣出几瓣桃花；
再让油腻织一层罗绮，
霉菌给他蒸出些云霞。

让死水酵成一沟绿酒，
漂满了珍珠似的白沫；
小珠们笑声变成大珠，
又被偷酒的花蚊咬破。

那么一沟绝望的死水，
也就夸得上几分鲜明。
如果青蛙耐不住寂寞，
又算死水叫出了歌声。

这是一沟绝望的死水，
这里断不是美的所在，
不如让给丑恶来开垦，
看他造出个什么世界。
* 临江仙·夜饮东坡醒复醉
宋 · 苏轼
夜饮东坡醒复醉，归来仿佛三更。家童鼻息已雷鸣。敲门都不应，倚杖听江声。
长恨此身非我有，何时忘却营营。夜阑风静縠纹平。小舟从此逝，江海寄余生。
* 钗头凤·世情薄
宋 · 唐婉
世情薄，人情恶，雨送黄昏花易落。晓风干，泪痕残。欲笺心事，独语斜阑。难，难，难！
人成各，今非昨，病魂常似秋千索。角声寒，夜阑珊。怕人寻问，咽泪装欢。瞒，瞒，瞒！
* 西江月·世事一场大梦
宋 · 苏轼
世事一场大梦，人生几度秋凉。夜来风叶已鸣廊。看取眉头鬓上。酒贱常愁客少，月明多被云妨。中秋谁与共孤光。把盏凄然北望。
* 《思远人·红叶黄花秋意晚》
宋代-晏几道
红叶黄花秋意晚，千里念行客。飞云过尽，归鸿无信，何处寄书得。
泪弹不尽临窗滴。就砚旋研墨。渐写到别来，此情深处，红笺为无色。
* 天末怀李白
唐代，杜甫
凉风起天末，君子意如何？
鸿雁几时到？江湖秋水多。
文章憎命达，魑魅喜人过。
应共冤魂语，投诗赠汨罗。
* 临江仙·千里长安名利客
宋 · 刘彤
千里长安名利客，轻离轻散寻常。难禁三月好风光。满阶芳草绿，一片杏花香。
记得年时临上马，看人眼泪汪汪。如今不忍更思量。恨无千日酒，空断九回肠。
* 如梦令·常记溪亭日暮
宋 · 李清照
常记溪亭日暮，沉醉不知归路。
兴尽晚回舟，误入藕花深处。
争渡，争渡，惊起一滩鸥鹭。
* 满江红·豫章滕王阁
宋，吴潜
万里西风，吹我上、滕王高阁。正槛外、楚山云涨，楚江涛作。何处征帆木末去，有时野鸟沙边落。近帘钩、暮雨掩空来，今犹昨。
秋渐紧，添离索。天正远，伤飘泊。叹十年心事，休休莫莫。岁月无多人易老，乾坤虽大愁难著。向黄昏、断送客魂消，城头角。
* 忆秦娥·箫声咽
唐·李白
箫注声咽，秦娥梦断注秦楼月。秦楼月，年年柳色，灞陵注伤别。
乐游原注上清秋节，咸阳古道注音尘绝。音尘绝，西风残照注，汉家注陵阙。
